feat/5675 - add an api token verification for api entreprise
betagouv/demarches-simplifiees.fr pull request #5698
Opened 2020-10-19 09:37 UTC by kara22

#5675

2020-10-19 15:58 UTC, kara22 commented
Cette PR ajoute un renforcement de sécurité au niveau de la validation du token. 

Actuellement, on vérifie que le token (JWT) est bien au bon format. Avec ce que j'ajoute en plus, on vérifie qu'il est bien valide au niveau de l'API entreprise avec l'endpoint **privileges**

Un token peut etre au bon format, mais pas valide au niveau de l'API. Maintenant les deux sont vérifiés pour éviter de polluer la base et sentry avec des mauvais token

2020-10-27 15:57 UTC, LeSim requested changes

2020-10-27 15:57 UTC, LeSim commented on app/controllers/new_administrateur/procedures_controller.rb
> +      if !@procedure.update(procedure_params) || token.has_key?(:errors)
Ne faudrait-il pas vérifier d'abords que le token n'a pas d'erreur pour éviter un update avec un token invalide ?

2020-10-27 15:57 UTC, LeSim commented on app/lib/api_entreprise/api.rb
> +      JSON.parse(response.body, symbolize_names: true)
```suggestion
    if response.success? || response.code&.between?(400, 499)
      JSON.parse(response.body, symbolize_names: true)
```

A tester ?

2020-10-27 15:57 UTC, LeSim commented on spec/controllers/new_administrateur/procedures_controller_spec.rb
> +  describe 'PATCH #jeton', vcr: { cassette_name: 'update_jeton' } do
je vois pas de nouvelle cassette, je ne comprends pas ce `vcr`

2020-10-27 15:57 UTC, LeSim commented on spec/controllers/new_administrateur/procedures_controller_spec.rb
>      let(:valid_token) { "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c" }
peut être l'appeler `invalid_token` et lui donner une valeur facilement lisible comme invalide

2020-10-27 16:48 UTC, kara22 commented on app/controllers/new_administrateur/procedures_controller.rb
> +      if !@procedure.update(procedure_params) || token.has_key?(:errors)
Yes, bien vu ! Merci. Mais du coup si la personne rentre "pouet" ça fait un appel API . Ou si non je rajoute un &&. COmme ça il check le format, si le format est bon ensuite il check le token afin d'éviter trop d'appels inutiles

2020-10-28 09:41 UTC, LeSim commented on app/controllers/new_administrateur/procedures_controller.rb
> +      if !@procedure.update(procedure_params) || token.has_key?(:errors)
ok, alors tu pourrais peut être faire un 

```
token = params[:procedure][:api_entreprise_token]
token_privileges = ApiEntreprise::API.privileges(token)

@procedure.api_entreprise_token = token

if @procedure.invalid? || token_privileges.has_key?(:errors)
  flash.now.alert = "Mise à jour impossible : le jeton n'est pas valide"
elsif @procedure.save
  flash.notice = 'Le jeton a bien été mis à jour'
else  
  flash.now.alert = @procedure.errors.full_messages
end

render 'jeton'
```

2020-11-09 09:40 UTC, LeSim requested changes

2020-11-09 09:40 UTC, LeSim commented on app/lib/api_entreprise/api.rb
> +    if response.success? || response.code&.between?(400, 499)
je comprends pas trop si c'est `response.code&.between?(400, 499)` alors on est en erreur non ?

2020-11-09 09:40 UTC, LeSim commented on app/lib/api_entreprise/privileges_adapter.rb
> +class ApiEntreprise::PrivilegesAdapter < ApiEntreprise::Adapter
Il me semble que tu ne te sers nul part de cette classe. J'ai l'impression que si on suit le design actuel, tu devrais utiliser  `ApiEntreprise::PrivilegesAdapter.new(token).to_params` dans ton controller au lieu de passer directement par ton api

2020-11-09 09:40 UTC, LeSim commented on spec/controllers/new_administrateur/procedures_controller_spec.rb
> +      response = Typhoeus::Response.new(code: 200, body: { :errors => ["Votre token n'est pas valide ou n'est pas renseigné"] })
L'api renvoie un code `200` quand le token n'est pas valide ?

2020-11-09 09:40 UTC, LeSim commented on spec/controllers/new_administrateur/procedures_controller_spec.rb
> +        expect(response.body).to eq({ :errors => ["Votre token n'est pas valide ou n'est pas renseigné"] })
tu triches, tu testes ton propre objet.  Par ailleurs, je ne te vois pas réaliser l'action `patch` ! Il te faudrait au moins 1 cas passant !

2020-11-09 17:20 UTC, kara22 commented
Merci @LeSim pour ce pair d'anthologie 🙏

2020-11-09 19:40 UTC, LeSim approved these changes

2020-11-09 19:40 UTC, merged