Création du modèle expert
betagouv/demarches-simplifiees.fr pull request #5846
Opened 2021-01-19 14:05 UTC by kara22

- Crée un modèle Expert pour les experts au lieu qu'ils soient instructeurs
- Ajoute une relation Experts<>Procedures pour facilement retrouver tous les experts d'une démarche et toutes les démarches sur lesquelles un expert intervient

2021-01-20 12:30 UTC, tchak commented on app/controllers/concerns/create_avis_concern.rb
> +        ExpertsProcedure.find_or_create_by(procedure: dossier.procedure, expert: avis.expert)
boujer dans `demander_un_avis!` ?

2021-01-20 12:33 UTC, tchak approved these changes

2021-01-20 17:20 UTC, LeSim requested changes
c'est bien mais il me semble qu'il y a un pb sur la liaison avis <-> expert. Tel que c'est fait, le code permet a un expert de donner son avis sur un dossier sans apparaître dans la table `experts_procedures`

2021-01-20 17:20 UTC, LeSim commented on app/models/experts_procedure.rb
> +  validates :expert, uniqueness: { scope: :procedure }
On peut ajouter une contrainte au niveau de la db pour vérifier ça ?

2021-01-20 17:20 UTC, LeSim commented on spec/models/expert_spec.rb
> -require 'rails_helper'
il me semble que ce commit est à supprimer

2021-01-20 17:20 UTC, LeSim commented on app/models/avis.rb
> +  belongs_to :expert, optional: true
heu ... non, pour moi l'avis doit être lié à une entrée de la table expert <-> procedure . De cette façon on sera sur de lister tous les experts qui ont donnée un avis sur une procédure en faisant un
`select expert_id from experts_procedures where procedure_id = xxx`

2021-01-20 17:35 UTC, tchak commented on app/models/avis.rb
> +  belongs_to :expert, optional: true
J'ai l'impression que c'est une histoire de join. Si l’on fait comme tu dis, alors il faudra un join à chaque fois qu'on veut l'expert de l'avis. Si l’on fait comme c'est fait actuellement il faudra un join pour avoir tous les avis d'une démarche. La question étant quelle opération est plus courante. Mais peut-être que je me trompe. On en parle demain.

2021-01-21 16:15 UTC, tchak commented on app/models/experts_procedure.rb
> +  has_many :avis
`dependent: :destroy` ?

2021-01-21 20:54 UTC, LeSim commented on app/models/avis.rb
> +  belongs_to :experts_procedure, optional: true
on ajouterait pas un `has_one :expert, through: :experts_procedure` ou un truc comme ça ?

2021-01-21 21:19 UTC, LeSim reviewed
J'ai l'impression que c'est toujours pas bon à cause des notifications sur les avis. Mais on s'approche :) .

Est ce que tu as testé manuellement que
- [ ] on pouvait toujours demander l'avis d'un expert (il reçoit un mail et peu répondre)
- [ ] la notification marche bien pour les nouveaux avis
- [ ] que si tu as un avis déjà lu, la tache after party ne le marque pas en non lu
- [ ] inversement, si tu as un avis non lu

2021-01-21 21:19 UTC, LeSim commented on lib/tasks/deployment/20210118142539_backfill_experts_procedure_id_on_avis_table.rake
> +        avis.update(experts_procedure: experts_procedure)
```suggestion
        avis.update_column(:experts_procedure_id: experts_procedure.id)
```

Les notifications des avis sur la page dossier se base sur la dernière fois qu'un avis a été modifié (`updated_at` voir [la](https://github.com/betagouv/demarches-simplifiees.fr/blob/f698dc798ca303e4df81a26c0ad53f5a124a0c4a/app/models/instructeur.rb#L124)). J'ai l'impression que cette tache allait modifier tout les `updated_at` et activer tous les avis. Je me gourre ?

2021-01-22 09:45 UTC, kara22 commented on lib/tasks/deployment/20210118142539_backfill_experts_procedure_id_on_avis_table.rake
> +        avis.update(experts_procedure: experts_procedure)
Non tu ne te goures pas, il allait bien modifier tous les updated_at 😱

2021-01-22 14:37 UTC, LeSim approved these changes
C'est bon pour moi. :+1:

2021-01-22 14:55 UTC, merged