ETQ admin, je peux choisir qui sera notifié de la décision finale sur le dossier
betagouv/demarches-simplifiees.fr pull request #5864
Opened 2021-01-28 11:18 UTC by kara22

#5812

2021-02-01 09:02 UTC, LeSim reviewed
J'ai l'impression que y'a du travaille de découpage de commit à faire

2021-02-01 09:02 UTC, LeSim commented on app/controllers/new_administrateur/procedures_controller.rb
> +      @experts_procedure = ExpertsProcedure.invited_experts(@procedure)
par contre, ce changement la ne devrait t'il pas être avec le commit précédent histoire d'avoir un changement cohérent ?

2021-02-01 11:58 UTC, LeSim requested changes

2021-02-01 11:58 UTC, LeSim commented on app/controllers/new_administrateur/procedures_controller.rb
> +      @experts_procedure = ExpertsProcedure.invited_experts(@procedure)
```suggestion
      @experts = @procedure.experts
```

Il te manquera peut être un `sort` . Du coup j'ai l'impression que la méthode `ExpertsProcedure.invited_experts` ne sert plus.

2021-02-01 11:58 UTC, LeSim commented on app/controllers/new_administrateur/procedures_controller.rb
> +      @expert_procedure.toggle!(:allow_decision_access)
1. J'ai l'impression que tu ne vérifies pas qui a la droit de modifier l accès a la décision, c'est a dire que n'importe qui avec la bonne requête pourrait activer cette feature
2. Pourquoi fais tu une affectation ?

```suggestion
      @procedure
        .experts_procedures
        .find(params[:expert_procedure])
        .toggle!(:allow_decision_access)
```

2021-02-01 16:15 UTC, kara22 commented on app/controllers/new_administrateur/procedures_controller.rb
> +      @experts_procedure = ExpertsProcedure.invited_experts(@procedure)
Dans ce cas j'ai besoin instances de ExpertsProcedure (et non pas experts) car je boucle dedans pour rendre notifiable les experts.

2021-02-04 09:12 UTC, LeSim reviewed
Je retire le bloqueur car je n'ai pas de temps tout de suite. J'ai l'impression néanmoins qu'il faut supprimer la méthode ` def self.invited_experts` de `experts_procedures` et mettre un sort qq part pour afficher les mails dans l'ordre alphabétique.

2021-02-04 09:12 UTC, LeSim approved these changes

2021-02-04 10:14 UTC, kara22 commented
Merci d’avoir débloqué @sim pour ton info j’ai viré la méthode qui ne servait plus et j’ai rajouté ça pour l’ordre alphabétique par mail :
@experts_procedure = @procedure.experts_procedures.sort_by{|expert_procedure| expert_procedure.expert.email }

2021-02-04 12:47 UTC, kemenaran commented on app/controllers/new_administrateur/procedures_controller.rb
> +        .toggle!(:allow_decision_access)
Je ne trouve pas l'endroit où on se sert effectivement de la valeur de `:allow_decision_access` pour envoyer l'email de notification ou non ; c'est normal ?

Si c'est pas encore implémenté, peut-être que c'est un peu bizarre d'afficher un switch qui n'est pas opérant pour l'instant ?

2021-02-04 12:47 UTC, kemenaran commented on app/views/new_administrateur/procedures/invited_expert_list.html.haml
> +          %th Notifiable
Je pense qu'il faudrait être plus clair sur indiquer ce que font les toggle-switches. 

Peut-être quelque chose comme :

```suggestion
          %th Notifier des décisions sur les dossiers
```

2021-02-04 12:47 UTC, kemenaran commented on app/views/new_administrateur/procedures/invited_expert_list.html.haml
> +                %span.toggle-switch-label.off
Ça m'inquiète un peu qu'on ait d'un côté le Javascript qui affiche le switch, et de l'autre une méthode `toggle` qui prend l'état existant sur le serveur et inverse la valeur. J'ai l'impression que si deux usagers ont le même onglet ouvert, ils vont modifier la valeur les uns des autres sans rien comprendre.

Pour blinder ça, j'ai l'impression que le mieux serait d'éviter d'avoir une méthode qui toggle, mais plutôt qu'elle puisse récupérer une valeur "true" ou "false" envoyée par la page. Comme ça on est raccord entre que voit le client et ce que reçoit le serveur.

Pour ça on pourrait utiliser une checkbox toggle-switch de base, dans un mini-formulaire ad-hoc. Un truc du genre (en pseudo code) :

```haml
  = form_with model: expert_procedure, url: admin_procedure_update_decision_access_path(expert_procedure: expert_procedure), remote: true do |f|
    = f.check_box :allow_decision_access, class: 'toggle-switch-checkbox', onchange: 'this.form.submit()'
```

Comme ça la checkbox se chargerait toute seule de savoir si elle est cochée ou pas, et quand on clique ou la change ça envoie le formulaire en remote au serveur, _avec la valeur de la checkbox_. On peut donc savoir côté serveur si l'admin a demandé à cocher la case ou pas.

2021-02-04 13:42 UTC, kemenaran commented on app/controllers/new_administrateur/procedures_controller.rb
> +        .toggle!(:allow_decision_access)
Vu avec Kara : on peut mettre ça derrière un feature flag en attendant que les emails soient réellement envoyés

2021-02-09 08:35 UTC, kemenaran requested changes

2021-02-09 08:35 UTC, kemenaran commented on app/controllers/new_administrateur/procedures_controller.rb
> +        .toggle!(:allow_decision_access)
@kara22 je crois que `toggle_allow_decision_access` ne se sert pas vraiment de la valeur `allow_decision_access` envoyée par le formulaire, et fait un toggle dans tous les cas.

Je pense qu'il faudrait plus renommer cette action en `update_allow_decision_access`, et faire en sorte qu'elle regarde le contenu de `params[:allow_decision_access]`.

2021-02-09 08:35 UTC, kemenaran commented on app/controllers/new_administrateur/procedures_controller.rb
> +        .toggle!(:allow_decision_access)
Et aussi autre question : niveau contrôle d'accès on est bon ? N'importe qui ne peut pas modifier le experts_procedure de qq d'autre ?

2021-02-09 10:16 UTC, kemenaran commented on spec/models/experts_procedure_spec.rb
> +        it { expect(procedure.experts).to eq([expert, expert2, expert3]) }
On a sans doute un problème de random sur ce test : y'a pas de raison que `procedure.expert` soit trié, du coup ce test va sans doute échouer aléatoirement.

Faut voir si on veut trier la relation (par prénom, par nom ?), ou si on veut faire une comparaison non-ordonnée avec `match_array`.

2021-02-09 10:16 UTC, kemenaran commented on spec/views/new_administrateur/procedures/invited_expert_list.html.haml_spec.rb
> +      expect(@invited_experts).to eq([experts_procedure, experts_procedure2])
Pareil, problème d'ordre random ici, faut trier la relation ou utiliser un `match_array`.

2021-02-09 14:13 UTC, kara22 commented on app/controllers/new_administrateur/procedures_controller.rb
> +        .toggle!(:allow_decision_access)
yes niveau contrôle on est bons grâce au before action sur @procedures dans le procedures_controller

2021-02-10 14:21 UTC, kemenaran requested changes

2021-02-10 14:21 UTC, kemenaran commented on app/views/new_administrateur/procedures/invited_expert_list.html.haml
> +                  url: admin_procedure_update_allow_decision_access_path(expert_procedure: expert_procedure, allow_decision_access: !expert_procedure.allow_decision_access),remote: true,
Ici je crois que ce formulaire passe le `allow_decision_access` deux fois : une fois dans l'URL du formulaire, en query-params, et une fois via la checkbox (en paramètre POST).

L'URL est sans doute le mauvais endroit où passer le paramètre, parce qu'elle n'est pas mise à jour quand la checkbox change. Donc le contrôleur va potentiellement récupérer la mauvaise valeur.

Normalement si on arrête juste de passer le paramètre en query-param dans l'URL, le contrôleur devrait prendre en compte le paramètre dans le formulaire à la place (en Rails `params` contient les paramètres query-params **et** de formulaire, tout fusionnés).

```suggestion
                  url: admin_procedure_update_allow_decision_access_path(expert_procedure: expert_procedure), remote: true,
```

2021-02-11 16:11 UTC, kemenaran approved these changes

2021-02-11 16:11 UTC, kemenaran commented
/rebase

2021-02-11 20:10 UTC, closed without merging