#5871 - Allow mailers/_bizdev_signature to be configured in .env file
betagouv/demarches-simplifiees.fr pull request #5872
Opened 2021-02-01 16:27 UTC by dzc34

Fixed #5871 "ETQ Ops, je souhaite personnaliser l'adresse postale du mail "Activez votre compte administrateur"" / @adullact

##  Actuellement

Lorsqu'on installe sa propre instance DS sans modifier le code source,
l'adresse postale du mail "**Activez votre compte administrateur**" n'est pas personnalisable.

Le mail "**Activez votre compte administrateur**" contient les 2 lignes suivantes 
qu'ils seraient souhaitables de pouvoir configurer :
```
Incubateur de Services Numériques / beta.gouv.fr
Services du Premier Ministre, 20 avenue de Ségur, 75007 Paris 
```

Ces 2 lignes sont écrites en dur dans le fichier [`app/views/layouts/mailers/_bizdev_signature.html.haml`](https://github.com/betagouv/demarches-simplifiees.fr/blob/dev/app/views/layouts/mailers/_bizdev_signature.html.haml). 

### Reproduction

- à partir d'un compte `super-admin` d'une instance DS personnalisée
- ajouter un nouveau compte **Administrateur**
- consulter le message "Activez votre compte administrateur"

![Sélection_025](https://user-images.githubusercontent.com/6709977/106485027-7848f100-64b0-11eb-938d-71073e626dbf.png)

## Comportement attendu

Rendre configurable l'adresse postale du mail "**Activez votre compte administrateur**" , via des variables d'environnements optionnelles :
```env
# Personnalisation d'instance - Adresses postale de l'opérateur de l'instance
CONTACT_ADRESS_LINE1="Association Adullact"
CONTACT_ADRESS_LINE2="5 rue du Plan du Palais, 34000 Montpellier"
```

![Sélection_026](https://user-images.githubusercontent.com/6709977/106485055-7e3ed200-64b0-11eb-9ab8-6dad035aff4b.png)

## Implémentation

Ajouter au fichier  [`config/initializers/contacts.rb`](https://github.com/betagouv/demarches-simplifiees.fr/blob/dev/config/initializers/contacts.rb), deux variables d'environnements optionnelles pour l'adresse postale utilisée dans le mail "**Activez votre compte administrateur**" et les documenter dans le fichier  [`env.example.optional`](https://github.com/betagouv/demarches-simplifiees.fr/blob/dev/config/env.example.optional).

Fichier `config/initializers/contacts.rb` :
```ruby
CONTACT_ADRESS_LINE1 = ENV.fetch("CONTACT_ADRESS_LINE1", "Incubateur de Services Numériques / beta.gouv.fr")
CONTACT_ADRESS_LINE2 = ENV.fetch("CONTACT_ADRESS_LINE2", "Services du Premier Ministre, 20 avenue de Ségur, 75007 Paris")
```

## Rebase du code (si nécessaire)

Si besoin nous pouvons faire les rebases et/ou ajouter un utilisateur BetaGouv pour faire le rebase directement sur notre dépôt.

2021-02-02 14:05 UTC, kemenaran requested changes
Sinon bon pour moi sur le principe.

2021-02-02 14:05 UTC, kemenaran commented on config/env.example.optional
> +# CONTACT_ADRESS_LINE2="Services du Premier Ministre, 20 avenue de Ségur, 75007 Paris"
j'ai l'impression que plutôt que d'avoir deux variables d'env (une par ligne), on pourrait plutôt avoir une seule variable, et splitter la chaine sur les `\n`:

```suggestion
# Personnalisation d'instance - Adresses postale de l'opérateur de l'instance
# CONTACT_ADDRESS="Incubateur de Services Numériques / beta.gouv.fr\nServices du Premier Ministre, 20 avenue de Ségur, 75007 Paris"
```

Et dans le template HAML faire un genre de :
```
= CONTACT_ADDRESS.split("\n").safe_join('<br>')

2021-02-03 00:41 UTC, dzc34 commented on config/env.example.optional
> +# CONTACT_ADRESS_LINE2="Services du Premier Ministre, 20 avenue de Ségur, 75007 Paris"
Modification appliquée avec le code suivant dans le template HAML :
```ruby
= safe_join(CONTACT_ADDRESS.split("\n"), raw('<br>'))
```

2021-02-04 11:16 UTC, kemenaran approved these changes

2021-02-04 12:48 UTC, merged