4978 export dossiers proc
betagouv/demarches-simplifiees.fr pull request #6059
Opened 2021-04-06 13:46 UTC by krichtof

close #4978 

Cette PR permet aux instructeurs d'exporter tous les dossiers d'une procedure, si le fichier final pèse moins d'1 Go.

Pour chaque dossier, l'export comprend
- un export pdf du dossier
- les pièces justificatives
- les commentaires
- l'horodatage des opérations

L'archive crée par un instructeur pour une procédure donnée est disponible pour l'ensemble du groupe instructeur auquel il appartient.

Cette archive est purgée une semaine après sa création.

2021-04-06 14:24 UTC, krichtof commented
J'ai un test qui plante pour l'instant. Et avant de le modifier, j'aimerai mieux comprendre l'intention de ce test : 

https://github.com/betagouv/demarches-simplifiees.fr/blob/6fe7529e7cbbb54b86e77d1c2c2ce69e5f49b1d3/spec/controllers/instructeurs/dossiers_controller_spec.rb#L716

2021-04-06 15:43 UTC, tchak commented on app/controllers/instructeurs/archives_controller.rb
> +      if !helpers.feature_enabled_for?(:archive_zip_globale, procedure) || !procedure.publiee?
```suggestion
      if !procedure.feature_enabled?(:archive_zip_globale) || !procedure.publiee?
```

2021-04-06 16:33 UTC, krichtof commented on app/controllers/instructeurs/archives_controller.rb
> +      if !helpers.feature_enabled_for?(:archive_zip_globale, procedure) || !procedure.publiee?
Thx. Corrigé ici : https://github.com/betagouv/demarches-simplifiees.fr/pull/6059/commits/a5cd29a763a367f634471f28abd82dc316b8bca0

2021-04-13 16:07 UTC, kemenaran commented on app/services/procedure_archive_service.rb
> +    archive = Archive.create(
```suggestion
    archive = Archive.create!(
```

2021-04-13 16:07 UTC, kemenaran commented on app/controllers/instructeurs/archives_controller.rb
> +      ArchiveCreationJob.perform_later(procedure, current_instructeur, type, month)
Question ouverte : comme la création de l'archive est asynchrone, ça veut dire que quand la page des archives va être affichée après avoir demandé une archive, l'archive en cours de création n'apparaitra sans doute pas.

Est-ce qu'on ne gagnerait pas à :

- créer un nouveau record `Archive` de manière synchrone ici (par exemple avec un `ProcedureArchiveService.new(procedure).create_pending_archive(current_instructeur, type, month)`)
- Puis laisser le job lancer un genre de `ProcedureArchiveService.new(procedure).collect_archive_files(archive)` ?

Comme ça on serait sûr que l'archive apparait bien comme "En cours" dès que la page est rafraîchie.

Je ne sais pas, c'est p-ê un peu plus de complexité en rab – mais j'ai l'impression que ça peut donner l'impression d'un logiciel plus solide, et moins de message au support.

2021-04-13 16:46 UTC, tchak commented on app/controllers/instructeurs/archives_controller.rb
> +      ArchiveCreationJob.perform_later(procedure, current_instructeur, type, month)
Nous avons commencé à discuter de ça par zoom avec @krichtof. Et oui, je suis d'accord avec toi @kemenaran – il faut faire la même chose que ce qu'on fait déjà pour les exports de dossiers. `Archive.create_or_find()` puis lancer le job sur l'archive crée.

2021-04-15 08:25 UTC, krichtof commented on app/controllers/instructeurs/archives_controller.rb
> +      if !procedure.feature_enabled?(:archive_zip_globale) || !procedure.publiee?
Je plussoie :)

2021-04-19 15:41 UTC, krichtof commented on app/controllers/instructeurs/archives_controller.rb
> +      if !procedure.feature_enabled?(:archive_zip_globale) || !procedure.publiee?
Corrigé ici : https://github.com/betagouv/demarches-simplifiees.fr/pull/6059/commits/992cd7ce5aed182500065f2c5dbb6748256bff31

2021-04-19 15:46 UTC, krichtof commented on app/controllers/instructeurs/archives_controller.rb
> +      end
Plus élégant effectivement. Corrigé ici : https://github.com/betagouv/demarches-simplifiees.fr/pull/6059/commits/185e60cd6eea1b816c70c8846ef02888e482b1e3#diff-de8357dadc3616204fffe5a8418d715e9756512a87e653e04fafca42901dc9a9R32

2021-04-19 15:46 UTC, krichtof commented on app/controllers/instructeurs/archives_controller.rb
> +    def list_of_months
Corrigé ici : https://github.com/betagouv/demarches-simplifiees.fr/pull/6059/commits/185e60cd6eea1b816c70c8846ef02888e482b1e3#diff-de8357dadc3616204fffe5a8418d715e9756512a87e653e04fafca42901dc9a9R32

2021-04-19 15:48 UTC, krichtof commented on app/models/archive.rb
> +  MAX_DUREE_CONSERVATION_ARCHIVE = 1.week
Corrigé ici : https://github.com/betagouv/demarches-simplifiees.fr/pull/6059/commits/d208de27de08acfe0760672cfcc6c1d9a23f0cf8#diff-c09dacb6d3f7cb5da80b2258c00c9bf2dcaef1fffc86350f02e4dfaf22126c38R15

2021-04-19 15:50 UTC, krichtof commented on app/models/dossier.rb
> +  scope :termine_durant,              -> (month) do
Corrigé ici : https://github.com/betagouv/demarches-simplifiees.fr/pull/6059/commits/25dbf1498b9df4ee35867af03260d6d5f21cfb27#diff-98660dcb79b91063c89eb59f3b47709b0581ff76339fa3c9da13706e8b6667a2R172

2021-04-19 15:51 UTC, krichtof commented on app/services/procedure_archive_service.rb
> +      filename = "procedure-#{@procedure.id}-mois-#{I18n.l(month, format: '%Y-%m')}.zip"
Corrigé ici : https://github.com/betagouv/demarches-simplifiees.fr/pull/6059/commits/25dbf1498b9df4ee35867af03260d6d5f21cfb27#diff-c09dacb6d3f7cb5da80b2258c00c9bf2dcaef1fffc86350f02e4dfaf22126c38R52

2021-04-19 15:52 UTC, krichtof commented on app/services/procedure_archive_service.rb
> +      # Les pièces justificatives
Supprimé ici : https://github.com/betagouv/demarches-simplifiees.fr/pull/6059/commits/25dbf1498b9df4ee35867af03260d6d5f21cfb27#diff-724b1e4df0c7b54938e7ddca5e9eec7b77f9ed4791b2420a134f0a6d2b94205fL32

2021-04-19 15:57 UTC, krichtof commented on app/services/procedure_archive_service.rb
> +  def self.poids_total_procedure(procedure)
Corrigé ici : https://github.com/betagouv/demarches-simplifiees.fr/pull/6059/commits/25dbf1498b9df4ee35867af03260d6d5f21cfb27#diff-724b1e4df0c7b54938e7ddca5e9eec7b77f9ed4791b2420a134f0a6d2b94205fR42

2021-04-19 15:57 UTC, krichtof commented on app/services/procedure_archive_service.rb
> +  def self.poids_total_dossiers(dossiers)
Corrigé ici : https://github.com/betagouv/demarches-simplifiees.fr/pull/6059/commits/25dbf1498b9df4ee35867af03260d6d5f21cfb27#diff-724b1e4df0c7b54938e7ddca5e9eec7b77f9ed4791b2420a134f0a6d2b94205fR46

2021-04-19 15:59 UTC, krichtof commented on app/views/instructeurs/archives/index.html.haml
> +    - if @dossiers_termines.count < 100 && @poids_total < 1.gigabyte
Corrigé ici : 
- https://github.com/betagouv/demarches-simplifiees.fr/pull/6059/commits/c3deca641cd8aee09f76aa5f5a9f85e03fd29de6#diff-8e346ad931f20fb4c84a510343a51bbe7b053e60fc6b3243519548ae6b841d52R1
- https://github.com/betagouv/demarches-simplifiees.fr/pull/6059/commits/c3deca641cd8aee09f76aa5f5a9f85e03fd29de6#diff-396c73eb444812cd9e84800bbd8b83421a5ece87ed711e8f14c5f74c5102dea2R33

2021-04-19 16:00 UTC, krichtof commented on app/views/instructeurs/archives/index.html.haml
> +            Rien à télécharger !
Nous sommes bien d'accord.

Corrigé ici : 
https://github.com/betagouv/demarches-simplifiees.fr/pull/6059/commits/c3deca641cd8aee09f76aa5f5a9f85e03fd29de6#diff-396c73eb444812cd9e84800bbd8b83421a5ece87ed711e8f14c5f74c5102dea2R47

2021-04-19 16:02 UTC, krichtof commented on db/migrate/20201104163658_create_archive_for_groupe_instructeur.rb
> +      t.bigint "groupe_instructeur_id", null: false
Corrigé ici : https://github.com/betagouv/demarches-simplifiees.fr/pull/6059/commits/d208de27de08acfe0760672cfcc6c1d9a23f0cf8#diff-f9d5dbdc5524b9501f5a7f8c5dbb076242fdd372267beef8146afe9a2c286631R1

2021-04-19 16:02 UTC, krichtof commented on db/migrate/20201104163658_create_archive_for_groupe_instructeur.rb
> +      t.string :content_type
Corrigé ici : https://github.com/betagouv/demarches-simplifiees.fr/pull/6059/commits/d208de27de08acfe0760672cfcc6c1d9a23f0cf8#diff-f9d5dbdc5524b9501f5a7f8c5dbb076242fdd372267beef8146afe9a2c286631R1

2021-04-19 16:04 UTC, krichtof commented on spec/controllers/instructeurs/archives_controller_spec.rb
> +      expect(ArchiveCreationJob).to receive(:perform_later).with(procedure1, instructeur, 'monthly', date_month)
Corrigé ici : https://github.com/betagouv/demarches-simplifiees.fr/pull/6059/commits/c3deca641cd8aee09f76aa5f5a9f85e03fd29de6#diff-66a6478d935ba57b740f87a353e7eb44fe38129238497fd4b047add161805a8eR44

2021-04-19 16:06 UTC, krichtof commented on spec/models/archive_spec.rb
> +      it { is_expected.to match_array([staled_archive]) }
Corrigé ici : https://github.com/betagouv/demarches-simplifiees.fr/pull/6059/commits/d208de27de08acfe0760672cfcc6c1d9a23f0cf8#diff-ec281efc8074d6a1f1d3576714c4f9020e5e98278f3d23fabf694f3f20b8f62eR14

2021-04-19 16:07 UTC, krichtof commented on app/views/instructeurs/archives/index.html.haml
> +                  Télécharger
Oui, effectivement, discuté avec @tchak .

Ce commit affiche la date à laquelle une archive a été lancée, ou générée : https://github.com/betagouv/demarches-simplifiees.fr/pull/6059/commits/e0c7ee869c3f6eb5840ad93f490c75d9a2d3790c

2021-04-19 16:13 UTC, krichtof commented on app/controllers/instructeurs/archives_controller.rb
> +      flash[:notice] = "Votre demande a été prise en compte. Selon le nombre de dossiers, cela peut prendre quelques minutes. Vous recevrez un courriel lorsque le fichier sera disponible."
Le flash fonctionne grâce au `render_flash` ici : https://github.com/betagouv/demarches-simplifiees.fr/pull/6059/commits/185e60cd6eea1b816c70c8846ef02888e482b1e3#diff-b346b1cc4df74e54595f1bbf8d8a2423935810e0c162dada48fd16943f7be12bR1

J'avoue que j'ai repris le code de @Keirua sans m'interroger de l'astuce utilisée.
Je peux faire un redirect vers la page d'index plus traditionnel à moins que @Keirua , tu as fait ce render pour pour une raison particulière ? Question perf peut-être ?

2021-04-20 08:19 UTC, krichtof commented on app/controllers/instructeurs/archives_controller.rb
> +      ArchiveCreationJob.perform_later(procedure, current_instructeur, type, month)
Oui, tout à fait ok avec cette proposition. Je fais ce commit dans la journée.

2021-04-21 15:45 UTC, krichtof commented on db/migrate/20201104163658_create_archive_for_groupe_instructeur.rb
> +      t.string :content_type
J'en ai profité également pour modifier le type du champ `month` en `date`, car nous n'avons pas besoin d'avoir la précision de l'heure

2021-04-21 15:59 UTC, krichtof commented on app/controllers/instructeurs/archives_controller.rb
> +      ArchiveCreationJob.perform_later(procedure, current_instructeur, type, month)
Cf ce commit : https://github.com/betagouv/demarches-simplifiees.fr/pull/6059/commits/76f2e37dc5d6b9bd78500c508ef007d581015212

2021-04-21 16:11 UTC, krichtof commented on app/controllers/instructeurs/archives_controller.rb
> +      flash[:notice] = "Votre demande a été prise en compte. Selon le nombre de dossiers, cela peut prendre quelques minutes. Vous recevrez un courriel lorsque le fichier sera disponible."
J'ai finalement fait un redirect vers la page d'index : https://github.com/betagouv/demarches-simplifiees.fr/pull/6059/commits/76f2e37dc5d6b9bd78500c508ef007d581015212

2021-04-21 16:39 UTC, krichtof commented
Merci pour tout le temps passé @kemenaran  pour cette review.
J'ai fait quelques commits temporaires qui intègrent tous tes retours.
Si ces corrections sont ok pour toi, je rebaserai alors, afin d'avoir un historique propre.

2021-04-22 07:41 UTC, kemenaran approved these changes
Yay, trop bien ; merci pour tout ton boulot !

2021-04-22 08:54 UTC, tchak requested changes

2021-04-22 08:54 UTC, tchak commented on app/services/procedure_archive_service.rb
> +  def create_pending_archive(instructeur, type, month = nil)
J'aurais vraiment préféré qu'on utilise `create_or_find_by` comme c’est le cas pour les exports. J'ai vraiment très peur des races conditions sur ce type d'objets. Ça nécessite d'introduire une clé de cache avec un index unique.

2021-04-22 08:55 UTC, tchak commented on app/services/procedure_archive_service.rb
> +  def create_pending_archive(instructeur, type, month = nil)
Si vous pensez vraiment que je surenchère, n'hésitez pas à ignorer :)

2021-04-27 07:54 UTC, krichtof commented on app/services/procedure_archive_service.rb
> +    if archive.nil?
@tchak J'ai peut-être mal compris mais je pensais que ceci répondait à ton intention. Je crée l'archive uniquement si je ne la trouve pas déjà.

2021-04-27 08:33 UTC, kemenaran commented on app/services/procedure_archive_service.rb
> +    if archive.nil?
Je pense que ce que veut dire @tchak , c'est qu'il y a une race-condition potentielle : deux serveurs applicatifs différents peuvent être en même temps en train de créer une archive, entre le check `nil?` et la création effective. La solution pour ça est de créer une contrainte en base qui force l'unicité - et de laisser `create_of_find` échouer à cause de la contrainte en base au besoin.

2021-04-27 09:38 UTC, tchak commented on app/services/procedure_archive_service.rb
> +    if archive.nil?
Effectivement, désolé j’aurais dû être plus précis. Voici un blog post qui explique bien la différence entre `find_or_create_by` et `create_or_find_by` https://bigbinary.com/blog/rails-6-adds-create_or_find_by

Et voici l'implémentation pour les exports https://github.com/betagouv/demarches-simplifiees.fr/blob/ba466f84308c0ec3c3284063b4a70bbe93c1d5dd/app/models/export.rb#L52-L55

2021-04-27 09:42 UTC, tchak commented on app/services/procedure_archive_service.rb
> +    if archive.nil?
Pour les exports l'index unique est sur la `key` + `forma`, pour les archives ça va être `key` + `content_type` + `month`.

En écrivant ceci, je me rends compte que je trouve aussi très perturbant le nom de la colonne `content_type`. Content type est un terme qui à une signification assez précise généralement associée aux mime types. Ici, ça n'a rien à voir.

2021-04-27 12:07 UTC, krichtof commented on app/services/procedure_archive_service.rb
> +    if archive.nil?
Merci, c'est plus clair pour moi. Je m'en occupe :)

2021-04-27 12:13 UTC, krichtof commented on app/services/procedure_archive_service.rb
> +    if archive.nil?
Et d'accord également avec ta remarque @tchak sur le nom `content_type`.  Je cherche une alternative mais pour l'instant, je n'ai rien de satisfaisant.
- frequency ? (sachant qu'actuellement, les valeurs possibles sont `monthly` ou `everything`)
- un boolean `monthly` qui vaut true si c'est une archive mensuelle, false si cela contient tous les dossiers (mais cela empêche plus tard d'ajouter facilement des archives annuelles par exemple)

Une idée ?

2021-04-27 12:14 UTC, kemenaran commented on app/services/procedure_archive_service.rb
> +    if archive.nil?
`time_span` ?

2021-04-27 12:15 UTC, kemenaran commented on app/services/procedure_archive_service.rb
> +    if archive.nil?
Ou `time_span_type`, si on veut être clair sur le fait que c'est un enum et pas un range de dates ?

2021-04-27 16:57 UTC, krichtof commented on app/services/procedure_archive_service.rb
> +    if archive.nil?
Ce commit fait le renommage : https://github.com/betagouv/demarches-simplifiees.fr/pull/6059/commits/ae21e040da654ff67a225de441bf2497b6ba1e99

2021-04-27 16:58 UTC, krichtof commented on app/services/procedure_archive_service.rb
> +    if archive.nil?
Et ce commit utilise le create_or_find_by : https://github.com/betagouv/demarches-simplifiees.fr/pull/6059/commits/893b841f4d10259471638e49a212061c78509e7b

2021-04-28 09:21 UTC, tchak approved these changes

2021-04-28 10:16 UTC, merged