ETQ usager, je veux que pouvoir supprimer les dossiers terminés
betagouv/demarches-simplifiees.fr pull request #6628
Opened 2021-11-10 16:37 UTC by kara22

#6536

2021-11-24 11:45 UTC, tchak commented on app/views/instructeurs/procedures/show.html.haml
> +            %tr{ class: [p.hidden_by_user_at.present? && "file-hidden-by-user"] }
on peut ajouter une méthode sur dossier `hidden_by_user?`

2021-11-24 11:49 UTC, tchak commented
Je suis un peu inquiet à l'idée d'introduire une nouvelle terminologie "cacher". Du point de vue de l'usager, il demande une suppression. J'appellerai ça "Demander la suppression". Je trouve que l’intention est plus claire.

2021-11-24 12:11 UTC, mfo commented on config/locales/fr.yml
> +      other: traités
il manquerait pas cette trad en anglais ?

2021-11-24 12:16 UTC, mfo commented on app/controllers/users/dossiers_controller.rb
> +      flash.notice = "Le dossier n° #{dossier.id} est caché. Il ne s'affichera plus sur votre interface."
il manque une trad ici

2021-11-24 12:18 UTC, mfo requested changes
Well done! il manque une trad dans le controller. sur les fichiers de trads je suis etonné qu'en anglais le noeud "traité" n'apparaisse pas (p-e la par le passé?).
Sinon coté a11y/ux Il faudrait indiquer que le dossier a été caché par l'utilisateur avec du texte en plus de la couleur (idée, sous le statut actuel)
cf: https://stephaniewalter.design/fr/blog/accessibilite-et-couleurs-outils-et-ressources-pour-concevoir-des-produits-accessible/
> Concernant l’accessibilité et les couleurs, il y a 2 grandes choses dont vous devez vous souvenir :
>    N’utilisez pas la couleur comme seul moyen visuel de véhiculer une information, une action, etc.
>    Veillez à ce que le rapport de contraste entre le premier plan (texte ou icônes, mais aussi les bordures et autres éléments de formulaire) et le fond soit suffisant.

2021-11-24 13:00 UTC, kara22 commented on app/views/instructeurs/procedures/show.html.haml
> +            %tr{ class: [p.hidden_by_user_at.present? && "file-hidden-by-user"] }
En gros ici c'est la projection qui met à dispo un hash a la vue. Pour des soucis de perf on a pas accès au dossier directement et dans le hash on a une clé : `hidden_by_user_at` @tchak

2021-11-24 13:01 UTC, kara22 commented on config/locales/fr.yml
> +      other: traités
Yes bien vu @mfo ✌🏾

2021-11-24 19:32 UTC, tchak commented on app/views/instructeurs/procedures/show.html.haml
> +            %tr{ class: [p.hidden_by_user_at.present? && "file-hidden-by-user"] }
Je pense que tu bluffes :) Je pense que `p` c'est une instance de modèle dossier, mais avec seulement les attributs sélectionné par la projection depuis la db

2021-11-24 19:35 UTC, tchak commented
Alors, je suis très pour mettre du texte dans l'UI mais il faut qu'on trouve une solution pour pas que la ligne fasse un kilomètre de haut :p Peut–être, vous pouvez pairé avec @mfo pour nous trouvé une solution élégante ? :)

2021-11-24 20:11 UTC, kara22 commented
Je viens de re proposer une autre solution qui garde la même hauteur de ligne @tchak

2021-11-24 20:13 UTC, kara22 commented on app/views/instructeurs/procedures/show.html.haml
> +            %tr{ class: [p.hidden_by_user_at.present? && "file-hidden-by-user"] }
Oui voilà je n’ai pas su l'exprimer correctement :) Je veux bien qu'on en discute @tchak, pourquoi on devrait mettre une méthode à la place de l'attribut sélectionné par la projection ?

2021-11-25 10:16 UTC, kemenaran commented on app/assets/stylesheets/dossiers_table.scss
> +  background-color: #FFCCCB;
Pinaillage : j'ai l'impression que pour les utilisateurs le rouge est souvent associé à un état en erreur.

Du coup pour indiquer les dossiers qui ont été supprimés par l'utilisateur, je proposerais bien soit du orange (notre couleur standard pour attirer l'attention), soit peut-être du violet ?

2021-11-25 10:16 UTC, kemenaran commented on app/views/users/dossiers/_dossier_actions.html.haml
> +- has_hide_action = dossier.termine? && dossier.hidden_by_user_at.nil?
Je pense qu'il faut modifier aussi `has_actions` sur la ligne au dessus :

```suggestion
- has_hide_action = dossier.termine? && dossier.hidden_by_user_at.nil?
- has_actions = has_edit_action || has_delete_action || has_new_dossier_action || has_transfer_action || has_hide_action
```

2021-11-25 10:16 UTC, kemenaran commented on spec/views/users/dossiers/_dossier_actions.html.haml_spec.rb
> +    it { is_expected.not_to have_link('\n\nSupprimer le dossier\n\n') }
Pourquoi on a besoin de rajouter les sauts de ligne explicitement ?

2021-11-25 10:16 UTC, kemenaran commented on app/views/instructeurs/procedures/show.html.haml
> +                  %a.cell-link{ href: path }= "#{column} #{ '- ' + t('views.instructeurs.dossiers.deleted_by_user') if p.hidden_by_user_at.present?}"
Pinaillage : peut-être qu'on gagne à découper en deux lignes ici ? 

Quelque chose comme :

```suggestion
                  %a.cell-link{ href: path }
                    = column
                    = "- #{t('views.instructeurs.dossiers.deleted_by_user')}" if p.hidden_by_user_at.present?
```

2021-11-25 10:44 UTC, tchak commented
@kara22 top, merci :)

2021-11-25 10:52 UTC, kara22 commented on spec/views/users/dossiers/_dossier_actions.html.haml_spec.rb
> +    it { is_expected.not_to have_link('\n\nSupprimer le dossier\n\n') }
Le test match avec les sauts de ligne

2021-11-25 11:50 UTC, kara22 commented on app/assets/stylesheets/dossiers_table.scss
> +  background-color: #FFCCCB;
@kemenaran J’ai ajouté la couleur orange avec une opacité à 0.6, j'ai mis la capture d'écran je te laisse me dire si ça te va

2021-11-25 12:43 UTC, kemenaran commented on app/assets/stylesheets/dossiers_table.scss
> +  background-color: #FFCCCB;
Pour moi c'est impec 👍

2021-11-26 08:36 UTC, mfo approved these changes

2021-11-26 08:51 UTC, merged