ETQ développeur, j'aimerais que mon environnement de développement soit accessible depuis un hôte autre que localhosot:3000 #6860
betagouv/demarches-simplifiees.fr pull request #6902
Opened 2022-02-04 13:43 UTC by akarzim

# Résumé

L'environnement de développement peut être accessible depuis un hôte autre que `localhost:3000` ; c'est par exemple le cas lors de l'utilisation de Démarches Simplifiées dans un environnement dockerisé.

Pour un parfait support de l'hôte personnalisé, il convient d'utiliser la variable d'environnement `APP_HOST` lors de la configuration de l'environnement de développement. Notamment, au niveau des routes, d'ActiveMailer, et de la liste blanche des hôtes.

Cela afin de prévenir, entre autres, ce type d'erreur :

```
*** ArgumentError Exception: Missing host to link to! Please
provide the :host parameter, set default_url_options[:host],
or set :only_path to true
```

mots-clés : ActiveMailer, env, dev, host, mailer, routes

ticket #6860 / @adullact & @synbioz

--- 

> - L'ADULLACT a mandaté le prestataire @synbioz pour développer plusieurs fonctionnalités (tickets et PR à venir).
> - C'est dans ce cadre que @synbioz nous propose certains correctifs annexes comme celui-ci.
> - Si c'est nécessaire, @akarzim et @jobygoude de @synbioz pourront interagir avec l'équipe @betagouv sur ce ticket et sur la PR (répondre aux commentaires, pousser des commits…).

## Rebase du code (si nécessaire)

Si besoin nous pouvons faire les rebases et/ou ajouter un utilisateur @betagouv pour intervenir directement sur notre dépôt.

---

`trackingAdullactContrib`

2022-02-04 14:38 UTC, LeSim commented on config/environments/development.rb
> +  config.hosts << ENV.fetch("APP_HOST", "localhost:3000")
Est ce que ce n'est pas redondant avec la ligne 115 ?

2022-02-07 09:34 UTC, akarzim commented on config/environments/development.rb
> +  config.hosts << ENV.fetch("APP_HOST", "localhost:3000")
Ce qui est redondant, c'est la déclaration d'une valeur par défaut si la variable d'environnement `APP_HOST` n'existe pas. Ce qui peut être résolu par un remaniement général de la gestion des variables d'environnement pour coller davantage aux conventions de Rails. (cf. l'échange autour du ticket #6878). Je vais d'ailleurs créer un ticket dédié à ce sujet.

En revanche, whitelister les hôtes et déclarer les options d'URL par défaut pour les routes sont deux choses différentes et complémentaires. Il n'y a là aucune redondance et nous avons bien besoin de ces deux déclarations.

2022-02-09 11:38 UTC, kemenaran requested changes
Sur le principe ça me semble bon 👍 

Après comme `APP_HOST` est une variable d'environnement obligatoire, je dirais qu'on peut partir du principe qu'elle sera toujours là, et ne pas mettre sa valeur par défaut (avoir juste un `ENV.fetch('APP_HOST')`.

2022-02-09 16:08 UTC, kemenaran approved these changes

2022-02-15 08:01 UTC, merged