Support de MailCatcher dans l'environnement de production
betagouv/demarches-simplifiees.fr pull request #6914
Opened 2022-02-04 17:15 UTC by akarzim

# Résumé

Proposition du support de MailCatcher dans l'environnement de production.

documentation : https://mailcatcher.me/

mots-clés : env, mailcatcher, smtp

ticket #6871 / @adullact & @synbioz

--- 

> - L'ADULLACT a mandaté le prestataire @synbioz pour développer plusieurs fonctionnalités (tickets et PR à venir).
> - C'est dans ce cadre que @synbioz nous propose certains correctifs annexes comme celui-ci.
> - Si c'est nécessaire, @akarzim et @jobygoude de @synbioz pourront interagir avec l'équipe @betagouv sur ce ticket et sur la PR (répondre aux commentaires, pousser des commits…).

## Rebase du code (si nécessaire)

Si besoin nous pouvons faire les rebases et/ou ajouter un utilisateur @betagouv pour intervenir directement sur notre dépôt.

---

`trackingAdullactContrib`

2022-02-06 04:35 UTC, mfo commented
je pense que cette PR solutionne ce prob : https://github.com/betagouv/demarches-simplifiees.fr/pull/6821

2022-02-07 08:49 UTC, akarzim commented
> je pense que cette PR est une meilleure piste pr ce prob (en gros pouvoir rajouter un type de delivery method) : #6821

Ah tout à fait ! Je n'avais pas connaissance de cette PR. Ça me semble parfaitement approprié et moins brouillon.
Je propose une refacto de cette MR une fois la #6821 mergée.

2022-02-09 07:48 UTC, akarzim commented
> Par ailleurs, si le refacto de cette PR peut être l'introduction de quelques variables générales `SMTP_HOST`, `SMTP_USER`, `SMTP_PASSWORD`, pour pouvoir facilement configurer un service SMTP générique, ça me semblerait top.

Dans ce cas, ça impliquerait d'utiliser cette méthode de livraison du courrier comme solution de repli en lieu et place de Mailjet, non ? D'ailleurs, `action_mailer.delivery_method = :smtp` est déjà supporté… à la réflexion, je ne suis pas certain que la méthode de livraison générique soit une bonne idée 🤔 Si tu vois une manière élégante et pertinente de l'implémenter, je te propose que ce soit fait dans un second temps :)

2022-02-09 11:41 UTC, kemenaran requested changes
L'approche me va ; juste p-ê un renommage des variables d'env ⬇️

2022-02-09 11:41 UTC, kemenaran commented on config/env.example
> +# When enabled, all emails will be sent using this provider
👍

2022-02-09 11:41 UTC, kemenaran commented on config/initializers/mailcatcher.rb
> +      port: ENV.fetch("SMTP_PORT")
D'accord, effectivement c'est p-ê pas le moment de mettre un SMTP générique 👍 

Est-ce que dans ce cas tu pourrais renommer ces variables en `MAILCATCHER_HOST` et `MAILCATCHER_PORT`, et les rajouter à `config/env.example` pour documenter qu'elles existent ?

2022-02-09 15:54 UTC, kemenaran approved these changes

2022-02-15 08:40 UTC, merged