Rendre le footer configurable
betagouv/demarches-simplifiees.fr pull request #6920
Opened 2022-02-04 17:37 UTC by akarzim

# Résumé

Proposition de paramétrage du footer par le moyen de variables d'environnement pour faire apparaitre ou non tout ou partie des liens dans le footer.

mots-clés : env, footer, link

ticket #6878 / @adullact & @synbioz

--- 

> - L'ADULLACT a mandaté le prestataire @synbioz pour développer plusieurs fonctionnalités (tickets et PR à venir).
> - C'est dans ce cadre que @synbioz nous propose certains correctifs annexes comme celui-ci.
> - Si c'est nécessaire, @akarzim et @jobygoude de @synbioz pourront interagir avec l'équipe @betagouv sur ce ticket et sur la PR (répondre aux commentaires, pousser des commits…).

## Rebase du code (si nécessaire)

Si besoin nous pouvons faire les rebases et/ou ajouter un utilisateur @betagouv pour intervenir directement sur notre dépôt.

---

`trackingAdullactContrib`

2022-02-15 14:45 UTC, kemenaran requested changes
Dans la dernière discussion qu'on a eu avec l'équipe, on s'est dit qu'un souci de cette PR était que les textes définis dans des variables d'env ne seraient plus localisables.

J'imagine qu'à la limite, quelque chose qu'on pourrait prendre serait quelque chose comme :

```haml
- if DOC_NOUVEAUTES_URL.present?
  = link_to 'Nouveautés', DOC_NOUVEAUTES_URL, target: '_blank'

- if CGU_URL.present?
  = link_to 'CGU / Mentions légales', CGU_URL, target: '_blank'

- # etc…
```

Ça permettrait à la fois de garder le texte localisable, et de ne pas multiplier les variables d'env. Et puis après, dans les cas qui nécessitent plus de configuration, je dirais que ça nécessiterait pour les instances de modifier la vue directement.

@akarzim tu en penses quoi ?

2022-02-15 15:06 UTC, akarzim commented
> Ça permettrait à la fois de garder le texte localisable, et de ne pas multiplier les variables d'env. 

Dans ce cas il faut effectivement le localiser :

```ruby
- if DOC_NOUVEAUTES_URL.present?
  = link_to I18n.t('footer.doc_nouveautes_title'), DOC_NOUVEAUTES_URL, target: '_blank'

- if CGU_URL.present?
  = link_to I18n.t('footer.cgu_title'), CGU_URL, target: '_blank'

- # etc…
```

Cela demande aussi à mettre en place un mécanisme qui permette de charger un fichier de locales propres à une instance donnée. Mais on peut faire ça en deux étapes :

1. rendre les URL du footer paramétrables (variables d'env)
2. localiser les textes du footer.

> Et puis après, dans les cas qui nécessitent plus de configuration, je dirais que ça nécessiterait pour les instances de modifier la vue directement.

En revanche, modifier la vue n'est pas une option selon moi. C'est une pratique qui n'est pas souhaitable si l'on cherche à tendre vers un déploiement entièrement automatisable. Si l'on souhaite rendre le footer malléable à l'envie, peut-être faudrait-il songer, dans un troisième temps, à une interface d'administration permettant de personnaliser le template du footer.

2022-02-15 15:23 UTC, kemenaran commented
En tout cas on prend déjà 1. et 2. volontiers, je pense :)

2022-02-23 09:43 UTC, mfo commented
Je ré-itère mes reserves sur cette approche (réserves qui avaient déjà été idéntifiées par @tchak sur la prolifération des **variables d'env**) : 

1. du wording au travers de vars d'env... désormais je vois plus ça comme un problème plutôt qu'une solution : on passe a coté de l'I18n. Le problème étant exprimé, la solution aussi : a refactorer par le biais des interfaces de rails-I18n
2. du "branching" (pour de la personnalisation, afficher ou non une partie de l'interface). Malheureusement ça ne solutionne qu'une problèmatique, celle de l'addulact. 
3. des URLs au travers de vars d'env ; toujours sur de la personnalisation.

J'ai donc l'impression que la question de fond est comment offrir une solution de personnalisation. Ma proposition : https://github.com/mfo/demarches-simplifiees.fr/pull/2

A comprendre que c'est une ébauche mais voici les intérêts que j'y vois : 
1. ça ouvre la porte a de la personnalisation : sans que nous ayons a gérer de nouvelles vars d'env, a relire des PRs etc...
2. ça endigue au moins du coté de la personnalisation la prolifération des vars d'env avec en bonus : passer une partie de l'app sur l'I18n.
3. c'est plus ou moins compatible avec l'idée de : 
> Cela demande aussi à mettre en place un mécanisme qui permette de charger un fichier de locales propres à une instance donnée. 

Si c'est jouable avec un fichier de locale, ca passera avec un fichier fr.html.erb.

Pour aller plus loin ; peut-etre formaliser ce qui est "personnalisable" ? Genre via un readme (en gros au moins flecher les utilisateurs sur quels templates on recommande de personnaliser), des pointeurs spécifiques (limite un fichier de mapping genre customizable_view.yml)

2022-02-23 15:19 UTC, mfo commented
@akarzim ; je me demande donc à quel point c'est jouable pour vous d'avoir vos templates directement sur une branche liée à une prod (ex: une branch (ou une tache "d'injection" de fichiers) par env de prod ; en théorie se sont des fichiers non assujeti aux conflit ; donc pas de prob...). Ainsi : 
- vous personnalisez ce que vous voulez sans 
- sans aller/retour entre le coeur et votre instance 
- sans impact pour les autres instances. (ils pourront adopter le même process, fluide) 

Bref ; j'aimerais vraiment explorer cette solution simple qui pourrait nous permettre de sortir par le haut de cette soupe de var d'env, de PR, d'echanges...

2022-02-23 19:38 UTC, emsnytech commented
On gère le multilingue comment avec tout cela ?

2022-02-24 11:58 UTC, mfo commented
@emsnytech ; en l'état, ce n'est pas géré justement (techniquement, les formulations sont "en dur"). 

La proposition est en partie de sortir de cette approche pour utiliser les fonctions classiques pour le multilinguisme (pour notre version du site).
En parallel pour les autres instances, ils peuvent gerer ca comme ils le souhaitent (en modifiant nos fichiers de traductions, ou en mettant les formulations en dur dans le code)

Hésites a demander un compléments

2022-03-03 15:21 UTC, akarzim commented
Je viens de faire un petit POC sur mon poste pour vérifier une hypothèse. Cela concerne l'internationalisation (i18n) et l'idée étant de surcharger les traductions proposées par défaut par la DINUM, plutôt que de les écraser.

J'obtiens manière d'arriver à mes fins !

# 1. Tirer parti des locales régionalisées

Il s'agit ici de déclarer une locale personnalisée du type `fr-custom` ou `fr-adullact`. Elle prendrait le dessus sur `fr` et utiliserait cette dernière en solution de repli. Ça fonctionne, mais ça risque de causer des complications si l'usager décide de changer de locale (en ajoutant `locale=en` dans l'URL par exemple). C'est donc une approche astucieuse, mais casse-gueule 😛 

# 2. Surcharger les locales via le chemin de chargement

Ici l'approche est différente, on va simplement ajouter des locales supplémentaires que l'on chargera en dernier. Partageant les mêmes clés que les locales proposées par défaut par la DINUM, ces dernières seront surchargées par nos locales personnalisées qui prendront le dessus. L'astuce étant de charger tout ce petit monde dans le bon ordre 😉 

```diff
  config.i18n.default_locale = :fr                                                                     
  config.i18n.load_path += Dir[Rails.root.join('config', 'locales', '**', '*.{rb,yml}')]               
+ config.i18n.load_path += Dir[Rails.root.join('config', 'custom_locales', '**', '*.{rb,yml}')]        
  config.i18n.available_locales = [:fr, :en]                                                           
  config.i18n.fallbacks = [:fr]                                                                        
```

Cette dernière approche offre plusieurs avantages :  
- les valeurs par défaut sont internationalisées et peuvent être surchargées (ou non)
- n'importe quelle traduction peut être surchargées, ça ne se limite pas au footer
- ça ne demande aucune action particulière dans les vues ou contrôleurs
- la surcharge peut-être faite pour chacune des langues supportées
- pour surcharger, il suffit de déposer des fichiers complémentaires dans le dossier `config/custom_locales`
- la méthode est facilement appropriable par les gestionnaires d'instances
- possibilité de versionner (sur une branche dédiée) ses locales personnalisées sans craindre un quelconque conflit lors d'un rebase

Qu'en penses-tu @mfo ?

2022-03-04 17:03 UTC, akarzim commented
Voilà, on a quelque chose qui ressemble davantage à la proposition de @mfo avec utilisation de vues et locales personnalisées.

- les vues personnalisées se trouvent dans `app/custom_views` et sont ajoutées en tête du `view_path` afin qu'elles soient prioritaires ;
- les locales personnalisées se trouvent dans `config/custom_locales` et sont ajoutées en fin du `i18n.load_path` de façon à surcharger les locales par défaut.

Pourquoi `app/custom_views` et `config/custom_locales` ? Parce que `app/views` et `app/locales` sont préchargées par défaut par Rails ; on s'évite ainsi des déconvenues telles que double chargement ou autres joyeusetés. En outre, on retrouve une certaine symétrie et un même équilibre entre les niveaux d'arborescence.

J'ai fait l'exercice avec le footer de l'Adullact et j'arrive fort bien à reproduire le rendu attendu avec cette approche 😃

2022-03-07 08:41 UTC, mfo commented
je trouve la forme bien plus maintenable et flexible pour les autres instance. qu'en pensez-vous @tchak / @kemenaran ?

2022-03-08 10:51 UTC, kemenaran commented
Ça me semble raisonnable 👍

2022-03-08 12:53 UTC, mfo commented
@akarzim ; continuons le nettoyage ;
je ne trouve plus d'occurence des var d'env suivante : 
```
# Instance provider
PROVIDED_BY = ENV.fetch("PROVIDED_BY", "la DINUM")
PROVIDER_NAME = ENV.fetch("PROVIDER_NAME", "DINUM")
PROVIDER_TITLE = ENV.fetch("PROVIDER_TITLE", "Direction Interministérielle au Numérique")
PROVIDER_URL = ENV.fetch("PROVIDER_URL", "https://numerique.gouv.fr/")

PROVIDER_LOGO_SRC = ENV.fetch("PROVIDER_LOGO_SRC", "footer/logo-dinum.png")
PROVIDER_LOGO_ALT = ENV.fetch("PROVIDER_LOGO_ALT", "Logo DINUM")
PROVIDER_LOGO_HEIGHT = ENV.fetch("PROVIDER_LOGO_HEIGHT", "161")
PROVIDER_LOGO_WIDTH = ENV.fetch("PROVIDER_LOGO_WIDTH", "138")
```
tu peux `git rm -f config/initializers/provider.rb`

Aussi ; jouable pr toi d'ajouter le fichier de trad en ? je m'occupe des trads au besoin

2022-03-08 13:23 UTC, akarzim commented
@mfo merci pour tes retours ! On devrait être tout bon à présent :)

2022-03-08 16:49 UTC, mfo commented
Merci ! j'ai activé l'automerge. Reste à mettre a jour la branche (je crois qu'il reste 2/3 vars d'env qui pourraient être netoyé ; mais se pour une prochaine issue)

2022-03-10 15:50 UTC, kemenaran approved these changes

2022-03-10 16:35 UTC, merged