Personnalisation du thème CSS
betagouv/demarches-simplifiees.fr pull request #6921
Opened 2022-02-04 17:39 UTC by akarzim

# Résumé

Cette proposition permet de modifier le thème CSS d'une instance Démarches Simplifiées à l'aide d'une simple feuille de style personnalisée qui peut être servie statiquement.

mots-clés : couleur, css, thème

ticket #6879 / @adullact & @synbioz

--- 

> - L'ADULLACT a mandaté le prestataire @synbioz pour développer plusieurs fonctionnalités (tickets et PR à venir).
> - C'est dans ce cadre que @synbioz nous propose certains correctifs annexes comme celui-ci.
> - Si c'est nécessaire, @akarzim et @jobygoude de @synbioz pourront interagir avec l'équipe @betagouv sur ce ticket et sur la PR (répondre aux commentaires, pousser des commits…).

## Rebase du code (si nécessaire)

Si besoin nous pouvons faire les rebases et/ou ajouter un utilisateur @betagouv pour intervenir directement sur notre dépôt.

---

`trackingAdullactContrib`

2022-02-15 14:51 UTC, kemenaran requested changes
Sur le principe ça me semble raisonnable 👍

2022-02-15 14:51 UTC, kemenaran commented on config/initializers/stylesheet.rb
> +EXTERNAL_STYLESHEET = ENV.fetch("EXTERNAL_STYLESHEET", nil)
Si tu pouvais rajouter et documenter la variable dans `config/env.example.optional` ça serait top.

Et aussi, pinaillage : est-ce que c'est un chemin ou une URL ? Si c'est un chemin, que dirais-tu de `EXTERNAL_STYLESHEET_PATH` ? Et si c'est une URL, il faudrait sans doute un `EXTERNAL_STYLESHEET_URL`, avec une règle pour l'autoriser dans la politique CSP.

2022-02-15 14:51 UTC, kemenaran commented on app/assets/stylesheets/_colors.scss
> +}
Par curiosité, c'est quoi l'intérêt pour vous de définir ces variables au niveau du CSS ?

2022-02-15 15:10 UTC, akarzim commented on config/initializers/stylesheet.rb
> +EXTERNAL_STYLESHEET = ENV.fetch("EXTERNAL_STYLESHEET", nil)
Il s'agit d'un chemin. Va pour `EXTERNAL_STYLESHEET_PATH`, voire `CUSTOM_STYLESHEET_PATH` selon votre préférence :)

2022-02-15 15:11 UTC, kemenaran commented on config/initializers/stylesheet.rb
> +EXTERNAL_STYLESHEET = ENV.fetch("EXTERNAL_STYLESHEET", nil)
Entre les deux, comme tu préfères 🙇

2022-02-15 15:17 UTC, jobygoude commented on app/assets/stylesheets/_colors.scss
> +}
Cela permet d'overrider les couleurs css définies en var par une feuille de style externe sans build spécifique.
Cela ne peut pas être le cas avec les variables scss car elles sont compilées.

Autrement dit, avec un seul build on peut avoir plusieurs instances avec des thémes différents (car l'url de la feuille de style spécifique sera différente).

2022-02-17 14:32 UTC, mfo commented on config/initializers/stylesheet.rb
> +EXTERNAL_STYLESHEET = ENV.fetch("EXTERNAL_STYLESHEET", nil)
si c'est une URL ; attention aux CSP ;-)

2022-02-17 14:59 UTC, mfo requested changes
canon la PR :-) si `EXTERNAL_STYLESHEET_URL` peut être une URL ; faudrait l'ajouter au `content_security_policy.rb`

2022-03-02 16:02 UTC, dzc34 commented on app/assets/stylesheets/_colors.scss
> +$g700: var(--g700);
J'ai l'impression que la discussion dans le ticket sur la compatibilité IE 11 n'est pas prise en compte dans cette PR ?

> C'est possible de faire ça sans casser la compatibilité IE 11 ?
voir : https://github.com/betagouv/demarches-simplifiees.fr/issues/6879#issuecomment-1028169197

Comparatif via une [VM Windows avec IE11](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/)  entre DS.fr et l'instance Adullact qui a priori utilise déjà ce code :

| DS.fr | DS Adullact |
| ------ | ------ |
|  ![Capture d’écran de 2022-03-02 15-12-12](https://user-images.githubusercontent.com/6709977/156388529-db989293-9c80-451f-9b94-5d4862141cf8.png)   |  ![Capture d’écran de 2022-03-02 15-06-52](https://user-images.githubusercontent.com/6709977/156388681-bd2af7fc-73d9-4167-9fe3-e863ea21104e.png)        |
|  ![Capture d’écran de 2022-03-02 15-16-14](https://user-images.githubusercontent.com/6709977/156388714-2fc66437-b30e-457e-93b5-f394bda93122.png)   |      ![Capture d’écran de 2022-03-02 15-08-17](https://user-images.githubusercontent.com/6709977/156388744-862bf6c0-9ac5-4110-b349-0b4df890c27d.png)      |

2022-03-02 16:20 UTC, dzc34 commented
Pour une instance DS, utiliser des couleurs personnalisées peut casser l'**accessibilité** de l'application. C'est de la responsabilité du gestionnaire d'instance, mais dans le cas où cette PR serait acceptée, il serait intéressant de documenter ce point.

Exemple sur l'instance Adullact : 

Pour certains textes (où c'est une erreur d'accessibilité si le contraste est inférieur à **4.5**), 
 on passe d'un [contraste de **14.9**](https://app.contrast-finder.org/result.html?foreground=White&background=%23000091&ratio=4.5&isBackgroundTested=false&algo=Rgb&lang=fr) à un [contraste de **3.7**](https://app.contrast-finder.org/result.html?foreground=White&background=%230884F9&ratio=4.5&isBackgroundTested=true&algo=Rgb&lang=fr)
 
 Via [Asqatasun](https://app.asqatasun.org) :
 
![Screenshot 2022-03-02 at 16-14-39 Asqatasun accessibility testing Automated, reliable, efficient (really)](https://user-images.githubusercontent.com/6709977/156400942-93176f2a-7650-4f71-8da2-0c77dc5f498c.png)

2022-03-04 07:57 UTC, akarzim commented on app/assets/stylesheets/_colors.scss
> +$g700: var(--g700);
Effectivement, on n'en a pas fait mention ici et tu fais bien de le rappeler @dzc34 ! De mon côté, j'avais toujours cette contrainte en tête et tout récemment je me suis demandé si un polyfill ne pourrait pas nous aider à surmonter cette incompatibilité IE11. Après quelques recherches, je suis tombé sur cette implémentation prometteuse :  

https://jhildenbiddle.github.io/css-vars-ponyfill/#/

L'idée serait donc de combler le manque fonctionnel d'IE11 par un petit script JS, un polyfill, qui se chargerait d'interpréter correctement les instructions relatives aux variables CSS.

Le jour où on décide que nous ne supportons plus IE11, il suffira de ne plus faire appel à ce script.

2022-03-10 17:15 UTC, akarzim commented on config/initializers/stylesheet.rb
> +EXTERNAL_STYLESHEET = ENV.fetch("EXTERNAL_STYLESHEET", nil)
@mfo je viens de l'ajouter aux CSP.  En revanche, je ne sais pas s'il est possible de tester cette partie 🤔 Auriez-vous de bonnes pratiques à partager sur cet aspect ?

J'en ai profité pour renommer la variable d'environnement `CUSTOM_STYLESHEET` puisqu'il peut s'agir d'un chemin comme d'une URL. À la réflexion, on pourrait aussi opter pour `CUSTOM_STYLESHEET_URI`… à votre convenance.

2022-03-14 14:26 UTC, mfo commented on config/initializers/stylesheet.rb
> +EXTERNAL_STYLESHEET = ENV.fetch("EXTERNAL_STYLESHEET", nil)
@akarzim ; j'ai pas de bille sur ce sujet dsl. la seule idée qui me vient serait de faire tourner les tests systèmes, recolter les uris d'images, styles, js et les comparer au header ; mais ça me semble pas être le plus fiable/facile a faire (a l'opposé de faire que la chose soit bien d'entrée, et qu'on evite ce type de problème par un bon usage dans ce cas précis des vars d'env).

2022-03-15 04:20 UTC, dzc34 commented
> Pour une instance DS, utiliser des couleurs personnalisées peut casser l'**accessibilité** de l'application. C'est de la responsabilité du gestionnaire d'instance, mais dans le cas où cette PR serait acceptée, il serait intéressant de documenter ce point.
> 
> Exemple sur l'instance Adullact : Pour certains textes (où c'est une erreur d'accessibilité si le contraste est inférieur à **4.5**), on passe d'un [contraste de **14.9**](https://app.contrast-finder.org/result.html?foreground=White&background=%23000091&ratio=4.5&isBackgroundTested=false&algo=Rgb&lang=fr) à un [contraste de **3.7**](https://app.contrast-finder.org/result.html?foreground=White&background=%230884F9&ratio=4.5&isBackgroundTested=true&algo=Rgb&lang=fr)

Sur l'instance de l'Adullact nous avons décidé de ne plus personnaliser les couleurs pour ne pas introduire des régressions sur l'accessibilité. Cette contribution  peut toutefois servir à d'autre instance DS souhaitant personnaliser les couleurs (à leur charge de vérifier les contraintes de contraste pour leur instance DS).

2022-03-15 04:20 UTC, dzc34 commented
> Pour une instance DS, utiliser des couleurs personnalisées peut casser l'**accessibilité** de l'application. C'est de la responsabilité du gestionnaire d'instance, mais dans le cas où cette PR serait acceptée, il serait intéressant de documenter ce point.
> 
> Exemple sur l'instance Adullact : Pour certains textes (où c'est une erreur d'accessibilité si le contraste est inférieur à **4.5**), on passe d'un [contraste de **14.9**](https://app.contrast-finder.org/result.html?foreground=White&background=%23000091&ratio=4.5&isBackgroundTested=false&algo=Rgb&lang=fr) à un [contraste de **3.7**](https://app.contrast-finder.org/result.html?foreground=White&background=%230884F9&ratio=4.5&isBackgroundTested=true&algo=Rgb&lang=fr)

Sur l'instance de l'Adullact nous avons décidé de ne plus personnaliser les couleurs pour ne pas introduire des régressions sur l'accessibilité. Cette contribution  peut toutefois servir à d'autre instance DS souhaitant personnaliser les couleurs (à leur charge de vérifier les contraintes de contraste pour leur instance DS).

2022-03-15 07:38 UTC, kemenaran commented on app/assets/stylesheets/_colors.scss
> +$g700: var(--g700);
Pour l'instant, même si on a une grande bannière "Navigateur obsolète" sur IE11, je pense qu'il faut qu'on garde un "mode dégradé" qui fonctionne à peu près.

Du coup je dirais qu'on merge cette PR avec juste le EXTERNAL_STYLESHEET, et qu'on avise pour les couleurs après, avec un polyfill ou pas (mais dans l'immédiat je serais vaguement pour ne pas intégrer les couleurs custom pour l'instant, tant que c'est pas très nécessaire).

2022-03-15 07:41 UTC, kemenaran commented on config/initializers/stylesheet.rb
> +EXTERNAL_STYLESHEET = ENV.fetch("EXTERNAL_STYLESHEET", nil)
Pareil, ça ne me semble pas essentiel à tester de bout-en-bout (le rapport bénéfice-risques ne me semble pas très bon).

Éventuellement on pourrait faire comme @mfo propose : définir une custom stylesheet, y mettre une variable CSS spécifique, faire tourner un test système et exécuter une ligne de JS qui va vérifier que la variable CSS a bien été prise en compte. Mais c'est p-ê un peu compliqué.

2022-03-15 07:42 UTC, kemenaran commented on config/env.example.optional
> +# Instance customization: Path or URL of the custom stylesheet
```suggestion
# Instance customization: path or URL to a custom CSS stylesheet
```

2022-05-04 11:50 UTC, mfo commented
Du fait que cela ne soit plus un besoin, je me permet de fermer (moins de complexité, mieux on se porte)

2022-05-04 11:50 UTC, closed without merging