Désactivation de ClamAV
betagouv/demarches-simplifiees.fr pull request #6927
Opened 2022-02-04 17:54 UTC by akarzim

# Résumé

Cette proposition offre la possibilité de désactiver ClamAV.

mots-clés : antivirus, clamav, docker, env

ticket #6885 / @adullact & @synbioz

--- 

> - L'ADULLACT a mandaté le prestataire @synbioz pour développer plusieurs fonctionnalités (tickets et PR à venir).
> - C'est dans ce cadre que @synbioz nous propose certains correctifs annexes comme celui-ci.
> - Si c'est nécessaire, @akarzim et @jobygoude de @synbioz pourront interagir avec l'équipe @betagouv sur ce ticket et sur la PR (répondre aux commentaires, pousser des commits…).

## Rebase du code (si nécessaire)

Si besoin nous pouvons faire les rebases et/ou ajouter un utilisateur @betagouv pour intervenir directement sur notre dépôt.

---

`trackingAdullactContrib`

2022-02-08 14:41 UTC, kemenaran requested changes

2022-02-08 14:41 UTC, kemenaran commented on config/env.example.optional
> +
Je dirais qu'on peut carrément le mettre dans `config/env.example` comme variable d'environnement obligatoire ; ça me semble une fonctionnalité suffisamment cœur-d'usage pour qu'elle soit obligatoire.

2022-02-08 14:41 UTC, kemenaran commented on config/application.rb
> +    config.x.clamav.enabled = ENV.fetch("CLAMAV_ENABLED", "enabled") == "enabled"
J'aime bien l'usage de configuration custom dans Rails – mais là j'ai l'impression que ça rajoute un niveau d'indirection dont on n'a pas besoin.

À mon avis on peut juste accéder à la variable d'environnement directement dans le code (surtout qu'on ne l'utilise qu'une fois).

2022-02-08 14:41 UTC, kemenaran commented on app/services/clamav_service.rb
> +    if Rails.env.development? || !Rails.configuration.x.clamav.enabled
Si on part sur l'ajout d'une variable d'env, dans ce cas autant l'utiliser même en dévelopment :

```suggestion
    if ENV['CLAMAV_ENABLED'] == 'disabled'
```

(en plus par défaut il est désactivé dans `env.example`, donc pour un développement local ça sera bon par défaut.)

2022-02-08 15:44 UTC, akarzim commented on config/env.example.optional
> +
OK. Avec quelle valeur par défaut ? Sachant que `config/env.example` est utilisé pour définir les variables d'environnement de l'environnement de test du CI.

2022-02-08 16:00 UTC, akarzim commented on config/env.example.optional
> +
J'aurais tendance à laisser l'env de test se comporter comme les autres. En revanche, je surchargerais la valeur de cette configuration dans les tests du service ClamAV pour tester son comportement en fonction de la valeur de celle-ci.

2022-02-08 16:14 UTC, kemenaran commented on config/env.example.optional
> +
On peut faire ça, oui. Dans ce cas on aurait un truc du genre :

```ruby
class ClamavService
  mattr_accessor :enabled?, default: (ENV['CLAMAV_ENABLED'] == 'enabled')

  def safe_file?
    if !self.class.enabled?
      return true
    end
    
    # …
  end
end
```

et dans les tests :

```
before { ClamavService.enabled? = true }
```

Après du coup je me demande comment ça se fait que les tests passent en ce moment, vu que ClamAV doit être activé dans tout l'environnement de test, mais que le binaire n'est pas forcément là…

2022-02-08 16:17 UTC, kemenaran commented on config/env.example.optional
> +
Enfin pour clarifier, je dirais :

- Si pour configurer clamav on veut utiliser le système de RAILS_ENV, dans ce cas autant mettre la config dans `config.x.clamav.enabled`
- Mais si on veut directement configurer ClamAV au niveau de la classe, autant ne pas rajouter un niveau d'indirection avec la config rails - et avoir directement un initialiser qui fasse `Clamav.enabled? = ENV['CLAMAV_ENABLED'] == 'enabled'

2022-02-08 18:35 UTC, akarzim commented on config/env.example.optional
> +
La surcharge, je l'imaginais se faire directement au niveau du test, pas dans le service. Je viens de pousser une refacto avec la mise à jour des tests pour refléter ma proposition ;)

2022-02-09 13:52 UTC, kemenaran approved these changes

2022-02-15 08:21 UTC, merged