[OpenStack] Harmonisation du traitement du type de stocakge
betagouv/demarches-simplifiees.fr pull request #6929
Opened 2022-02-04 17:58 UTC by akarzim

# Résumé

Cette proposition concerne un petit nettoyage dans l'utilisation des variables d'environnement liées à OpenStack en systématisant l'usage de la variable `STORAGE_TYPE` en lieu et place de `FOG_ENABLED`.

mots-clés : env, fog, openstack, storage

ticket #6887 / @adullact & @synbioz

--- 

> - L'ADULLACT a mandaté le prestataire @synbioz pour développer plusieurs fonctionnalités (tickets et PR à venir).
> - C'est dans ce cadre que @synbioz nous propose certains correctifs annexes comme celui-ci.
> - Si c'est nécessaire, @akarzim et @jobygoude de @synbioz pourront interagir avec l'équipe @betagouv sur ce ticket et sur la PR (répondre aux commentaires, pousser des commits…).

## Rebase du code (si nécessaire)

Si besoin nous pouvons faire les rebases et/ou ajouter un utilisateur @betagouv pour intervenir directement sur notre dépôt.

---

`trackingAdullactContrib`

2022-02-08 14:37 UTC, kemenaran requested changes

2022-02-08 14:37 UTC, kemenaran commented on config/env.example
> +STORAGE_TYPE="local" # options: amazon, local, openstack
Je mettrais bien des commentaires en rab :

```suggestion
# ActiveStorage service to use for attached files.
# Possible values:
# - "local": store files on the local filesystem
# - "amazon": store files remotely on an S3 storage service
# - "openstack": store files remotely on an OpenStack storage service
#
# (See config/storage.yml for the configuration of each service.)
ACTIVE_STORAGE_SERVICE="local"

# Configuration for the OpenStack storage service (if enabled)
```

(J'ai aussi renommé STORAGE_TYPE en ACTIVE_STORAGE_SERVICE – mais si ça vous gonfle on peut rester sur l'ancienne valeur.)

2022-02-08 15:34 UTC, akarzim commented on config/environments/development.rb
> +  config.active_storage.service = ENV.fetch("STORAGE_TYPE", "local").to_sym
> Et aussi, on voudrait ce même réglage dans `production.rb`, non ?

Si tout à fait, bien vu ! C'était passé dans un autre commit sur une branche locale ! J'ajoute ça.

```ruby
# config/environments/production.rb
config.active_storage.service = ENV.fetch("STORAGE_TYPE", "openstack").to_sym
```

J'imagine que la même remarque s'applique ici ? Pas besoin de valeur par défaut.

2022-02-08 15:35 UTC, akarzim commented on config/env.example
> +STORAGE_TYPE="local" # options: amazon, local, openstack
> J'ai aussi renommé STORAGE_TYPE en ACTIVE_STORAGE_SERVICE – mais si ça vous gonfle on peut rester sur l'ancienne valeur.

Je préfèrerais renommer la constante et la variable dans un second temps pour éviter les conflits avec les autres PR en attente qui pourraient en dépendre.

2022-02-08 15:36 UTC, kemenaran commented on config/environments/development.rb
> +  config.active_storage.service = ENV.fetch("STORAGE_TYPE", "local").to_sym
Oui, pareil, je dirais "pas de valeur par défaut" (comme ça on évite le cas où la variable d'env serait définie, mais vide, et ça fallback magiquement sur un truc par défaut au lieu de planter.)

2022-02-08 15:43 UTC, kemenaran commented on config/env.example
> +STORAGE_TYPE="local" # options: amazon, local, openstack
Si tu te sens d'ouvrir la PR de renommage dans la foulée, yes, bon pour moi 👍 

(Comme ça en mergeant tout dans le bon ordre ça devrait le faire sans conflits)

2022-02-08 16:20 UTC, akarzim commented on config/environments/development.rb
> +  config.active_storage.service = ENV.fetch("STORAGE_TYPE", "local").to_sym
> comme ça on évite le cas où la variable d'env serait définie, mais vide, et ça fallback magiquement sur un truc par défaut au lieu de planter.

Euh… si la variable d'env est vide, dans tous les cas on n'est pas couvert ! Ça prendra la valeur vide et fera un `.to_sym`dessus. Le fecth nous garanti juste de lever une exception `KeyError` si la variable d'env n'existe pas, ce que ne ferait pas `[]`… mais on aurait un `NoMethodError` en tentant de faire un `to_sym` sur `nil`. 🙃

2022-02-09 16:08 UTC, kemenaran approved these changes

2022-02-15 09:38 UTC, merged