Configuration de l'URL de l'iframe Matomo
betagouv/demarches-simplifiees.fr pull request #6931
Opened 2022-02-04 18:03 UTC by akarzim

# Résumé

Configuration de l'URL de l'iframe Matomo par le moyen d'une variable d'environnement.

mots-clés : env, iframe, matomo

ticket #6889 / @adullact & @synbioz

--- 

> - L'ADULLACT a mandaté le prestataire @synbioz pour développer plusieurs fonctionnalités (tickets et PR à venir).
> - C'est dans ce cadre que @synbioz nous propose certains correctifs annexes comme celui-ci.
> - Si c'est nécessaire, @akarzim et @jobygoude de @synbioz pourront interagir avec l'équipe @betagouv sur ce ticket et sur la PR (répondre aux commentaires, pousser des commits…).

## Rebase du code (si nécessaire)

Si besoin nous pouvons faire les rebases et/ou ajouter un utilisateur @betagouv pour intervenir directement sur notre dépôt.

---

`trackingAdullactContrib`

2022-02-07 08:37 UTC, Dan33l commented on config/env.example
> +MATOMO_IFRAME_URL="https://matomo.organisme.fr/index.php?module=CoreAdminHome&action=optOut&language=fr&&fontColor=333333&fontSize=16px&fontFamily=Muli"
Pour information le domaine `organisme.fr` est réservé par quelqu'un.

La [RFC 2606](https://www.rfc-editor.org/rfc/rfc2606.html#page-2) recommande l'usage de `example.com`, `example.net`, ou `example.org`.

2022-02-07 09:09 UTC, akarzim commented on config/env.example
> +MATOMO_IFRAME_URL="https://matomo.organisme.fr/index.php?module=CoreAdminHome&action=optOut&language=fr&&fontColor=333333&fontSize=16px&fontFamily=Muli"
Je suis entièrement d'accord ! Cela vaudrait peut-être un ticket et une PR dédiés si l'on constate d'autres cas similaires ? Je vois par exemple : 
```toml
# config/env.example.optional
# Admins and instructeurs can freely change their email to these domains
# LEGIT_ADMIN_DOMAINS = "domaine_1.com;domaine_2.com"
```

2022-02-08 14:28 UTC, kemenaran requested changes

2022-02-08 14:28 UTC, kemenaran commented on config/initializers/urls.rb
> +MATOMO_IFRAME_URL = ENV.fetch("MATOMO_IFRAME_URL", "https://#{ENV.fetch('MATOMO_HOST', 'stats.data.gouv.fr')}/index.php?module=CoreAdminHome&action=optOut&language=fr&&fontColor=333333&fontSize=16px&
Si on rajoute `MATOMO_IFRAME_URL` dans `env.example`, alors on sait qu'elle fait partie des variables d'env obligatoires, et donc qu'elle sera forcément définie dans l'environnement au runtime.

Du coup je serais pour supprimer la valeur par défaut ici (et mettre une valeur vide si Matomo est désactivé).

```suggestion
MATOMO_IFRAME_URL = ENV.fetch("MATOMO_ENABLED") == "enabled" ? ENV.fetch("MATOMO_IFRAME_URL") : ""
```

2022-02-08 15:24 UTC, akarzim commented on config/initializers/urls.rb
> +MATOMO_IFRAME_URL = ENV.fetch("MATOMO_IFRAME_URL", "https://#{ENV.fetch('MATOMO_HOST', 'stats.data.gouv.fr')}/index.php?module=CoreAdminHome&action=optOut&language=fr&&fontColor=333333&fontSize=16px&
En effet. Cela dit, la valeur par défaut contient une URL aux nombreux paramètres assez génériques mais difficilement prévisibles. L'idée ici était plutôt de proposer des paramètres par défaut, mais surchargeables au besoin. Ainsi, j'aurais plutôt vu cette constante dans `env.example.optional`. Ce qui évite de forcer la définition d'une URL plutôt complexe. Qu'en penses-tu ?

2022-02-08 15:27 UTC, kemenaran commented on config/initializers/urls.rb
> +MATOMO_IFRAME_URL = ENV.fetch("MATOMO_IFRAME_URL", "https://#{ENV.fetch('MATOMO_HOST', 'stats.data.gouv.fr')}/index.php?module=CoreAdminHome&action=optOut&language=fr&&fontColor=333333&fontSize=16px&
Oui, tu as raison, ça m'a l'air bien de la mettre dans `env.example.optional` 👍

2022-02-09 11:43 UTC, kemenaran approved these changes

2022-02-09 11:49 UTC, merged