[OpenStack] nettoyage des variables d'environnement
betagouv/demarches-simplifiees.fr pull request #6932
Opened 2022-02-04 18:08 UTC by akarzim

# Résumé

Cette proposition concerne un petit nettoyage dans l'utilisation des variables d'environnement liées à OpenStack en systématisant l'usage de la variable `FOG_OPENSTACK_URL` en lieu et place de `FOG_BASE_URL`.

mots-clés : env, openstack, url

ticket #6890 / @adullact & @synbioz

--- 

> - L'ADULLACT a mandaté le prestataire @synbioz pour développer plusieurs fonctionnalités (tickets et PR à venir).
> - C'est dans ce cadre que @synbioz nous propose certains correctifs annexes comme celui-ci.
> - Si c'est nécessaire, @akarzim et @jobygoude de @synbioz pourront interagir avec l'équipe @betagouv sur ce ticket et sur la PR (répondre aux commentaires, pousser des commits…).

## Rebase du code (si nécessaire)

Si besoin nous pouvons faire les rebases et/ou ajouter un utilisateur @betagouv pour intervenir directement sur notre dépôt.

---

`trackingAdullactContrib`

2022-02-08 14:23 UTC, kemenaran requested changes

2022-02-08 14:23 UTC, kemenaran commented on config/env.example
> +STORAGE_TYPE="openstack"
J'ai l'impression que cette nouvelle variable `STORAGE_TYPE` n'est utilisée nulle part - alors que `FOG_ENABLED` est toujours utilisée dans `development.rb`.

J'avoue que je serais plutôt pour garder `FOG_ENABLED`, en l'état, qui m'a l'air plus simple au vu de l'usage actuel.

2022-02-08 14:23 UTC, kemenaran commented on config/env.example
> +FOG_OPENSTACK_AUTH_URL="https://auth.cloud.ovh.net"
👍

2022-02-08 14:23 UTC, kemenaran commented on config/initializers/urls.rb
> +FOG_OPENSTACK_AUTH_URL = ENV.fetch("FOG_OPENSTACK_AUTH_URL", "https://auth.cloud.ovh.net")
Cette nouvelle constante `FOG_OPENSTACK_AUTH_URL` n'est utilisée nulle part (vu qu'on essaie plutôt de taper dans la config définie dans `storage.yml`. Du coup je serais plutôt pour ne pas la mettre du tout.

```suggestion
```

2022-02-08 15:08 UTC, akarzim commented on config/env.example
> +STORAGE_TYPE="openstack"
Ici il faut prendre en considération les changements sur la PR #6929. `FOG_ENABLED` n'est plus utilisée, au profit de `STORAGE_TYPE` plus souple (non limité à `local` et `openstack`).

2022-02-08 15:12 UTC, akarzim commented on config/initializers/urls.rb
> +FOG_OPENSTACK_AUTH_URL = ENV.fetch("FOG_OPENSTACK_AUTH_URL", "https://auth.cloud.ovh.net")
J'ai tenté d'homogénéiser l'usage qui est fait des variables d'environnement. Actuellement, on préfère passer par une constante plutôt que directement par la variable d'environnement. Il y a des exceptions et tu as mis le doigt dessus. Pour rester cohérent avec le reste de l'app, c'est plutôt le fichier `storage.yml` qui devrait faire usage des constantes et non taper sur la variable d'env.

Pour aller plus loin dans la réflexion, cf. #6934

2022-02-08 15:14 UTC, akarzim commented on config/initializers/urls.rb
> +FOG_OPENSTACK_AUTH_URL = ENV.fetch("FOG_OPENSTACK_AUTH_URL", "https://auth.cloud.ovh.net")
Mais je suis d'accord, cette constante n'est pas utilisée et on peut s'en dispenser.

2022-02-08 15:17 UTC, akarzim commented on config/initializers/urls.rb
> +FOG_OPENSTACK_AUTH_URL = ENV.fetch("FOG_OPENSTACK_AUTH_URL", "https://auth.cloud.ovh.net")
Cependant, on perdrait la valeur par défaut. Est-ce acceptable ? Faut-il la conserver par un autre moyen ?

2022-02-08 15:17 UTC, kemenaran commented on config/env.example
> +STORAGE_TYPE="openstack"
Oui, désolé, j'ai dépilé les PR dans le mauvais ordre. Ça me va 👍

2022-02-08 15:19 UTC, kemenaran commented on config/initializers/urls.rb
> +FOG_OPENSTACK_AUTH_URL = ENV.fetch("FOG_OPENSTACK_AUTH_URL", "https://auth.cloud.ovh.net")
Bin de toute manière si on rajoute une variable d'env, on va devoir modifier les fichiers d'env en staging et en prod avant de proder (pour que l'appli démarre correctement). Du coup pour moi c'est pas grave de ne pas mettre la valeur par défaut (et puis de tt façon y'a un exemple de la valeur attendue dans config/env.example).

2022-02-08 16:08 UTC, akarzim commented on config/initializers/urls.rb
> +FOG_OPENSTACK_AUTH_URL = ENV.fetch("FOG_OPENSTACK_AUTH_URL", "https://auth.cloud.ovh.net")
> et puis de tt façon y'a un exemple de la valeur attendue dans config/env.example

Ah oui, tu as raison ! Je me fais des nœuds au cerveau tout seul 😅

2022-02-09 11:49 UTC, kemenaran commented on config/storage.yml
> +    openstack_auth_url: "<%= ENV['FOG_OPENSTACK_AUTH_URL'] %>"
Alors en fait j'ai vérifié : on a toujours une variable d'env FOG_OPENSTACK_URL, qu'on n'utilise pas pour l'instant, mais qui clairement est supposée être celle là.

Du coup je vais plutôt utiliser la variable d'env existante – plutôt que d'introduire une nouvelle variable `FOG_OPENSTACK_AUTH_URL`.

Je modifie la PR directement, si ça te va.

2022-02-09 11:53 UTC, kemenaran approved these changes

2022-02-09 12:07 UTC, merged

2022-02-09 13:49 UTC, akarzim commented on config/storage.yml
> +    openstack_auth_url: "<%= ENV['FOG_OPENSTACK_AUTH_URL'] %>"
OK. Attention cependant, on a deux URLs distinctes pour lesquelles il faut se mettre d'accord sur les variables qui les portent : 

```toml
FOG_OPENSTACK_AUTH_URL="https://auth.cloud.ovh.net"
FOG_OPENSTACK_URL="https://static.demarches-simplifiees.fr"
 ```

À la lecture de l'historique Git, j'ai constaté qu'il y a eu pas mal de micmac avec ces deux URLs. Je te laisse le soin de leur choisir un nom de variable qui te semble adéquat :)