turbo poll controller
betagouv/demarches-simplifiees.fr pull request #7266
Opened 2022-05-06 10:33 UTC by tchak

2022-05-10 14:32 UTC, mfo commented on app/components/attachment/edit_component.rb
> +  def self.text(form, file)
un peu confusant a la lecture de ne pas retomber sur des kwargs (cru que c'etait buggé mais non visible)

2022-05-10 14:47 UTC, mfo commented on app/views/attachments/destroy.turbo_stream.haml
> += turbo_stream.show_all ".attachment-input-#{@attachment.id}"
pas moyen de passer par le component Edit, ou un base pour ca ? en gros j'ai une petite crainte sur une desynchro future

2022-05-10 14:53 UTC, mfo commented on app/components/attachment/edit_component/edit_component.html.haml
> +.attachment
dans un monde il resterait a i18né les textes

2022-05-10 15:09 UTC, tchak commented on app/components/attachment/edit_component.rb
> +  def self.text(form, file)
j'ai porté le code existant. Je ne suis pas convaincu du pattern non plus. Je suis chaud pour en parler d'une autre API.

2022-05-10 15:11 UTC, tchak commented on app/views/attachments/destroy.turbo_stream.haml
> += turbo_stream.show_all ".attachment-input-#{@attachment.id}"
C'est du rélicat tout ça. J'ai un plan pour réduire ce genre d'usages. J'essaye de pas tout changer tout de suite.

2022-05-11 04:29 UTC, mfo commented on config/application.rb
> +    config.view_component.use_global_output_buffer = true
```suggestion
    config.view_component.use_global_output_buffer = true # see: https://viewcomponent.org/known_issues.html
```

2022-05-11 04:30 UTC, mfo commented on app/views/champs/piece_justificative/show.js.erb
> -<% if attachment.virus_scanner.pending? %>
j'ai pas capté comment ca se replugger maintenant.

2022-05-11 04:31 UTC, mfo commented on app/views/instructeurs/dossiers/_state_button_refresh.js.erb
> -<% if attachment && attachment.virus_scanner.pending? %>
idem ; pas capté capté comment ca se replug maintenant.

2022-05-11 04:33 UTC, mfo commented on app/views/instructeurs/procedures/show.html.haml
> -          = render partial: "download_dossiers", locals: { procedure: @procedure, exports: @exports }
on perd l'accès aux archives zip si je ne me trompe ? p-e mettre le bouton don on a parlé ici : https://github.com/betagouv/demarches-simplifiees.fr/issues/7237

2022-05-11 04:34 UTC, mfo requested changes
franchement t'as envoyé du parpaing ; bravo. je trouve la nouvelle approche bien plus structuré (déjà a la relecture du code, les composant facilitent enormement la comprehension.).

Juste, j'ai l'impression qu'on perd l'accès aux archives. P-e qqch que j'ai raté?

2022-05-11 07:19 UTC, tchak commented
Pour les archives je veux passer une autre PR avant : #7286 

C'est une proposition. Si tu préfères une autre solution, parlons-en dans la PR.

2022-05-11 07:23 UTC, tchak commented
Pour la suppression des événements : à chaque "refresh" turbo va insérer un élément avec `data-controller="turbo-poll"` et stimulus va remettre dans le scheduler une requête. Je garde un état global pour traquer le nombre de retry et l'augmentation des intervalles.

2022-05-11 11:12 UTC, mfo commented on app/views/instructeurs/procedures/show.html.haml
> -          = render partial: "download_dossiers", locals: { procedure: @procedure, exports: @exports }
ok fixé par : https://github.com/betagouv/demarches-simplifiees.fr/pull/7286/files

2022-05-11 11:12 UTC, mfo approved these changes

2022-05-11 11:12 UTC, mfo commented
> Pour les archives je veux passer une autre PR avant : #7286
> 
> C'est une proposition. Si tu préfères une autre solution, parlons-en dans la PR.

c'est parfait :-)

2022-05-17 14:25 UTC, merged