fix: add administrateur with confirmation
betagouv/demarches-simplifiees.fr pull request #7736
Opened 2022-09-07 08:30 UTC by sebastiencarceles

When adding an administrateur, use the given email address instead of the current admin's one.

See #7699

# Avant

![Screenshot 2022-09-07 at 10-09-21 Détails démarche de test #1 - Tps](https://user-images.githubusercontent.com/1193334/188825925-75a18881-e65d-4c27-91f5-ebd8f6337773.png)

![image](https://user-images.githubusercontent.com/1193334/188826093-35a0025c-a35f-4df8-ae2a-97ce2b200870.png)

# Après

![image](https://user-images.githubusercontent.com/1193334/188830182-2f31b2c9-cabe-41dc-8384-43f7d1e72844.png)

2022-09-07 09:13 UTC, LeSim approved these changes

2022-09-07 09:28 UTC, sebastiencarceles commented
Merci pour la review @LeSim
Malheureusement je découvre que je n'ai pas les droits pour merger moi-même : 

![image](https://user-images.githubusercontent.com/1193334/188843722-300d4e3c-d8a5-40ac-8e2a-254789ab5fed.png)

Peux-tu me donner les droits ou merger ? Merci !

2022-09-07 09:42 UTC, tchak commented
Si on merge ça, ça veut dire qu'on peut approuvé l'ajout soit même...

2022-09-07 09:46 UTC, tchak requested changes
Il faut corriger l'implémentation de confirmation. Dans l'état actuel des choses, on peut ajouter n'importe quel email sauf le sien en confirmant soit même. De plus, l’implémentation est dangereuse selon moi. Le click sur le lien ajoute automatiquement l’administrateur et le lien contient l’email. Donc il y a la possibilité d’envoyer un lien forgé au support et si l’opérateur click dessus sans faire attention un administrateur sera crée.

2022-09-07 10:03 UTC, LeSim commented
Ouch, bien vu @tchak

2022-09-07 10:09 UTC, tchak commented
Je ne sais pas si on peut s'en sortir sans état. Peut-être en passant par un JWT (pour ne pas réinventer un conteneur signé) avec dedans l'email de celui qui demande l'ajout et l'email qui est demandé à être ajouté.

2022-09-07 16:31 UTC, tchak commented
J'ai détaillé la proposition d'implémentation dans cette issue : https://github.com/betagouv/demarches-simplifiees.fr/issues/7744

2022-09-08 08:45 UTC, sebastiencarceles commented
replaced by #7737

2022-09-08 08:45 UTC, closed without merging