DSFR: convert dossier top form elements
betagouv/demarches-simplifiees.fr pull request #7760
Opened 2022-09-13 12:38 UTC by colinux

Tant que j'étais sur la notice de procédure dans #7758, j'ai converti au DSFR en coordination avec @Olivier-Marcellin la zone où on affiche le lien vers cette notice (_Guide de la démarche_), ça concerne : 

- la notice à propos des champs obligatoires + auto save
- le bouton optionnel _Guide de la démarche_
- l'info optionnelle à propos d'un dossier déposé par un compte FranceConnect (le partial est aussi réutilisé dans un autre contexte pour les instructeurs) (grace au component _Tile_)

ça donne ça dans le contexte d'un dépôt de dossier :

<img width="800" alt="Capture d’écran 2022-09-13 à 14 24 34" src="https://user-images.githubusercontent.com/150279/189902227-b37004f1-93cb-4193-8d0c-8e9e345f71dc.png">

2022-09-13 12:39 UTC, colinux commented on app/javascript/entrypoints/main.css
> +
Tri alphabétique, on ajoute juste _tile_

2022-09-19 09:31 UTC, mfo commented on app/components/dsfr/notice_component.rb
> +class Dsfr::NoticeComponent < ApplicationComponent
la doc pointe verte un composant qui s'appelle alert, on le nomme notice. je suis surpris. possible d'aligner?

2022-09-19 09:31 UTC, mfo commented on app/components/dsfr/notice_component.rb
> +  def initialize(closable: false)
si on parle d'alert, il y a les differents, etat : dommage que se soit pas possible la non ?

2022-09-19 09:32 UTC, mfo commented on app/components/dsfr/notice_component/notice_component.html.haml
> +        %button.fr-btn--close.fr-btn{ title: t('.close_notice'), onclick: 'javascript:DS.closeNoticeInfo(event)' }
a la vue du code de DSFR ; je pense qu'on peux juste c/c leurs style plutot que rajouter qqch au namespace global non ?

cf: 
```
<button class="fr-btn--close fr-btn" title="Masquer le message" onclick="const alert = this.parentNode; alert.parentNode.removeChild(alert)">
        Masquer le message
    </button>
```

2022-09-19 09:38 UTC, mfo requested changes
top. en optim :

- il manque p-e une trad 
- l'impression qu'on peut simplifier le js
- il y a un lien vers la doc qu'est pas bon

2022-09-19 09:38 UTC, mfo commented on app/components/dsfr/notice_component.rb
> +# see: https://www.systeme-de-design.gouv.fr/elements-d-interface/composants/alerte
```suggestion
# see: https://www.systeme-de-design.gouv.fr/elements-d-interface/composants/bandeau-d-information-importante/
```

2022-09-19 09:38 UTC, mfo commented on config/locales/fr.yml
> +          notice: Guide de la démarche
ça m'etonne de pas voir les trads en ?

2022-09-19 11:48 UTC, mfo commented on app/javascript/entrypoints/main.css
> +
attention au tri alphabétique car le DSFR recommande d'inclure dans un ordre specifique : 

ex: ```cat ./node_modules/@gouvfr/dsfr/dist/component/footer/README.md```
```
# footer

Le pied de page propose des éléments d’information sur le site et une navigation secondaire pour l’utilisateur afin qu’il poursuive son parcours. Il est modulable selon les besoins et les exigences du site.

## Dépendances
```shell
footer
└─ core
└─ link
└─ logo
```

## Utilisation
Afin d’utiliser le composant `footer`, il est nécessaire d’ajouter les fichiers de styles et de scripts présents dans le dossier dist dans l'ordre suivant :\n
```html
<html>
  <head>
    <link href="css/core/core.min.css" rel="stylesheet">
    <link href="css/link/link.min.css" rel="stylesheet">
    <link href="css/logo/logo.min.css" rel="stylesheet">
    <link href="css/footer/footer.min.css" rel="stylesheet">
  </head>
  <body>
  </body>
</html>
```

## Documentation

Consulter [la documentation](https://gouvfr.atlassian.net/wiki/spaces/DB/pages/222331413/Pied+de+page+-+Footer) sur le module Pied de page%   ```

2022-09-19 11:50 UTC, colinux commented on app/components/dsfr/notice_component/notice_component.html.haml
> +        %button.fr-btn--close.fr-btn{ title: t('.close_notice'), onclick: 'javascript:DS.closeNoticeInfo(event)' }
Je suis pas sûr au moins 3 raisons :
- on n'utilise pas le code JS directement du DSFR
- il faudrait gérer la traduction à chaque fois
- c'est assez verbeux avec 5 niveaux d'indentation, ce qui rendrait les vues moins lisibles

mais à discuter si on prend le parti pris de ne faire des components que pour du code significatif. A la limite ça pourrait être juste un partial plutôt qu'un component (mais je ne sais pas si mixer partials & components ruby & pour le DSFR soit une bonne idée aussi)

2022-09-19 11:55 UTC, mfo commented on app/components/dsfr/notice_component/notice_component.html.haml
> +        %button.fr-btn--close.fr-btn{ title: t('.close_notice'), onclick: 'javascript:DS.closeNoticeInfo(event)' }
pardon je me suis mal exprimé, je pensais surtout au fait de pas faire du `DS.closeNoticeInfo(event)`. le code js inline me semble préférable.

2022-09-19 15:00 UTC, colinux commented on app/javascript/entrypoints/main.css
> +
Bien vu, j'ai réorganisé et explicité le fait qu'il ya bien des dépendances à respecter. Merci !

2022-09-19 15:05 UTC, colinux commented
OK en principe j'ai tout résolu, et j'ai réécrit le JS en stimulus (ce qui est trop bien, j'avais zappé qu'on avait ça merci pour le rappel!)

2022-09-21 13:44 UTC, tchak approved these changes

2022-09-21 14:44 UTC, merged