feat(conditonal): ajoute l'operator d'inclusion dans une liste pour le conditionnel
betagouv/demarches-simplifiees.fr pull request #7767
Opened 2022-09-15 15:56 UTC by LeSim

egalement : 
- refactor le système d'erreur pour des erreurs plus précises
- mise à jour du breadcrump et de la barre de résumé des options à chaque modification sur les conditions

2022-09-19 11:44 UTC, mfo requested changes
je pense que ca fera un super sujet pour notre point tech de demain. 
il y aurait p-e un peu de renamming pour facilité la lecture
+ l'impression qu'il manque une trad et qu'il y a du dupliqué

2022-09-19 11:44 UTC, mfo commented on app/models/logic/champ_value.rb
> +    enums: :enums,
curiosité, quelle est la diff singulier/pluriel ?

2022-09-19 11:44 UTC, mfo commented on app/models/logic.rb
>          Constant.new(left.options.first.second)
je me rends compte que je suis pas alaise avec ce concept de `first.second`. possible d'avoir un accesseur plus parlant ?

2022-09-19 11:44 UTC, mfo commented on app/models/logic/eq.rb
> +      !left.options.map(&:second).include?(right.value)
idem, j'ai des difficultés a comprendre ce map(&:second)

2022-09-19 11:44 UTC, mfo commented on app/models/logic/include_operator.rb
> +  def errors(_stable_ids = nil)
un petit commentaire m'aiderait a comprendre pourquoi on a un param non utilisé

2022-09-20 13:54 UTC, LeSim commented on app/models/logic/include_operator.rb
> +  def errors(_stable_ids = nil)
vu ensemble (avec bug a la clé !)

2022-09-22 11:36 UTC, mfo approved these changes

2022-09-26 08:28 UTC, merged